"""
BCGPT WebUI — FastAPI application entry point.

This module wires together all application components:
  - Configuration (env vars → app.state.config)
  - Middleware chain (CORS, CSRF, rate limiting, audit logging, etc.)
  - API routers (chat, models, retrieval, agents, admin, …)
  - Static file serving with SPA fallback
  - Lifecycle management (startup validation, background tasks, graceful shutdown)
"""

# ---------------------------------------------------------------------------
# Standard library
# ---------------------------------------------------------------------------
import asyncio
import json
import logging
import mimetypes
import os
import sys
import time
from contextlib import asynccontextmanager
from typing import Any
from urllib.parse import urlencode, parse_qs, urlparse

# ---------------------------------------------------------------------------
# Third-party
# ---------------------------------------------------------------------------
import aiohttp
from pydantic import BaseModel
from sqlalchemy import text

from fastapi import (
    Depends,
    FastAPI,
    HTTPException,
    Request,
    status,
    applications,
)
from fastapi.openapi.docs import get_swagger_ui_html
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles

from starlette.exceptions import HTTPException as StarletteHTTPException
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.middleware.sessions import SessionMiddleware
from starlette.responses import Response

# ---------------------------------------------------------------------------
# Application — utilities
# ---------------------------------------------------------------------------
from bcgpt.utils import (
    logger,
    start_logger,
    AuditLoggingMiddleware,
    SecurityHeadersMiddleware,
    OAuthManager,
    has_access,
    process_chat_payload,
    process_chat_response,
    get_sentinels_from_env,
)
from bcgpt.utils.rate_limit import InMemoryRateLimiter
from bcgpt.utils.csrf import CSRFProtectionMiddleware
from bcgpt.utils.error_handlers import (
    generic_exception_handler,
    validation_exception_handler,
    http_exception_handler,
)
from bcgpt.utils.auth import (
    get_license_data,
    decode_token,
    get_admin_user,
    get_verified_user,
)
from bcgpt.utils.models import (
    get_all_models,
    get_all_base_models,
    check_model_access,
)
from bcgpt.utils.chat import (
    generate_chat_completion as chat_completion_handler,
    chat_completed as chat_completed_handler,
    chat_action as chat_action_handler,
)
from bcgpt.utils.http_client import close_client_session
from bcgpt.utils.chat_generation import (
    ChatGenerationValidationError,
    parse_chat_generation_request,
    parse_uuid,
    verify_assistant_message_authority,
    verify_chat_generation_message_proof,
)

# ---------------------------------------------------------------------------
# Application — socket, providers
# ---------------------------------------------------------------------------
from bcgpt.socket.main import (
    app as socket_app,
    periodic_usage_pool_cleanup,
)
from bcgpt.providers import init_providers

# ---------------------------------------------------------------------------
# Application — routers
# ---------------------------------------------------------------------------
from bcgpt.routers import (
    audio,
    images,
    ollama,
    openai,
    gemini,
    claude,
    retrieval,
    pipelines,
    tasks,
    auths,
    channels,
    chats,
    folders,
    configs,
    groups,
    files,
    functions,
    memories,
    models,
    knowledge,
    prompts,
    evaluations,
    tools,
    users,
    utils,
    security,
    security_events,
    audit,
    usage,
    scim,
    handoff,
    dashboard,
    mcp as mcp_router,
)

from bcgpt.compliance.routers import (
    inventory as compliance_inventory,
    aiia as compliance_aiia,
    incidents as compliance_incidents,
    fairness as compliance_fairness,
    dsar as compliance_dsar,
    vendor as compliance_vendor,
    dashboard as compliance_dashboard,
)

from bcgpt.compliance.hitl.router import router as hitl_router
from bcgpt.routers.retrieval import (
    get_embedding_function,
    get_ef,
    get_rf,
)

# ---------------------------------------------------------------------------
# Application — agent subsystem
# ---------------------------------------------------------------------------
from bcgpt.agent.routers import (
    agents as agents_router,
    multi_agent as multi_agent_router,
    skills as skills_router,
)
from bcgpt.agent.config import (
    AGENT_DEFAULT_AUTONOMY_LEVEL,
    AGENT_OPERATOR_MAX_TOOL_ITERATIONS,
    AGENT_QUALITY_PIPELINE_ENABLED,
    AGENT_QUALITY_SAMPLING_RATE,
    WORKFLOW_ENGINE_ENABLED,
    WORKFLOW_DEFAULT_TIMEOUT,
    WORKFLOW_NODE_TIMEOUT,
    MULTI_AGENT_ENABLED,
    MULTI_AGENT_MAX_PARALLEL,
    MULTI_AGENT_DEBATE_ROUNDS,
    MULTI_AGENT_CONSENSUS_THRESHOLD,
    QUALITY_CLAIM_DECOMPOSITION_ENABLED,
    QUALITY_GROUNDING_ENABLED,
    QUALITY_DOC_GRADING_ENABLED,
    QUALITY_CLAIM_MODEL,
    QUALITY_GROUNDING_MODEL,
    QUALITY_DOC_GRADING_MODEL,
    QUALITY_ENTAILMENT_MODEL,
    QUALITY_DEFAULT_MODEL,
    LETTUCE_DETECT_ENABLED,
    LETTUCE_DETECT_THRESHOLD,
)

# ---------------------------------------------------------------------------
# Application — internal / models
# ---------------------------------------------------------------------------
from bcgpt.internal import Session, engine
from bcgpt.models import Functions, Models, Users, Chats, ChatGenerations

# ---------------------------------------------------------------------------
# Application — configuration
# ---------------------------------------------------------------------------
from bcgpt.config import (
    AppConfig,
    reset_config,
    LICENSE_KEY,
    # Audit
    AUDIT_LOG_LEVEL,
    AUDIT_EXCLUDED_PATHS,
    MAX_BODY_LOG_SIZE as AUDIT_MAX_BODY_LOG_SIZE,
    AUDIT_LOG_FILE_ROTATION_SIZE,
    AUDIT_RETENTION_DAYS,
    # Ollama
    ENABLE_OLLAMA_API,
    OLLAMA_BASE_URLS,
    OLLAMA_API_CONFIGS,
    # OpenAI
    ENABLE_OPENAI_API,
    ONEDRIVE_CLIENT_ID,
    OPENAI_API_BASE_URLS,
    OPENAI_API_KEYS,
    OPENAI_API_CONFIGS,
    # Direct Connections
    ENABLE_DIRECT_CONNECTIONS,
    # MCP (Model Context Protocol) servers
    ENABLE_MCP_SERVERS,
    MCP_SERVERS,
    MCP_ALLOWED_HOSTS,
    MCP_BUILTINS_ENABLED,
    # Image
    AUTOMATIC1111_API_AUTH,
    AUTOMATIC1111_BASE_URL,
    AUTOMATIC1111_CFG_SCALE,
    AUTOMATIC1111_SAMPLER,
    AUTOMATIC1111_SCHEDULER,
    COMFYUI_BASE_URL,
    COMFYUI_API_KEY,
    COMFYUI_WORKFLOW,
    COMFYUI_WORKFLOW_NODES,
    ENABLE_IMAGE_GENERATION,
    ENABLE_IMAGE_PROMPT_GENERATION,
    ENABLE_IMAGE_PROMPT_TRANSLATION,
    ENABLE_IMAGE_PROMPT_EXPANSION,
    IMAGE_GENERATION_ENGINE,
    IMAGE_GENERATION_MODEL,
    IMAGE_SIZE,
    IMAGE_STEPS,
    IMAGES_OPENAI_API_BASE_URL,
    IMAGES_OPENAI_API_KEY,
    IMAGES_GEMINI_API_BASE_URL,
    IMAGES_GEMINI_API_KEY,
    # Audio
    AUDIO_STT_ENGINE,
    AUDIO_STT_MODEL,
    AUDIO_STT_OPENAI_API_BASE_URL,
    AUDIO_STT_OPENAI_API_KEY,
    AUDIO_TTS_API_KEY,
    AUDIO_TTS_ENGINE,
    AUDIO_TTS_MODEL,
    AUDIO_TTS_OPENAI_API_BASE_URL,
    AUDIO_TTS_OPENAI_API_KEY,
    AUDIO_TTS_SPLIT_ON,
    AUDIO_TTS_VOICE,
    AUDIO_TTS_AZURE_SPEECH_REGION,
    AUDIO_TTS_AZURE_SPEECH_OUTPUT_FORMAT,
    PLAYWRIGHT_WS_URI,
    PLAYWRIGHT_TIMEOUT,
    FIRECRAWL_API_BASE_URL,
    FIRECRAWL_API_KEY,
    RAG_WEB_LOADER_ENGINE,
    DEEPGRAM_API_KEY,
    # Retrieval
    RAG_TEMPLATE,
    DEFAULT_RAG_TEMPLATE,
    RAG_FULL_CONTEXT,
    BYPASS_EMBEDDING_AND_RETRIEVAL,
    RAG_EMBEDDING_MODEL,
    RAG_EMBEDDING_MODEL_AUTO_UPDATE,
    RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE,
    RAG_RERANKING_MODEL,
    RAG_RERANKING_MODEL_AUTO_UPDATE,
    RAG_RERANKING_MODEL_TRUST_REMOTE_CODE,
    RAG_EMBEDDING_MODEL_URI,
    RAG_EMBEDDING_MODEL_API_KEY,
    RAG_RERANKING_MODEL_URI,
    RAG_RERANKING_MODEL_API_KEY,
    RAG_EMBEDDING_ENGINE,
    RAG_EMBEDDING_BATCH_SIZE,
    RAG_RELEVANCE_THRESHOLD,
    RAG_FILE_MAX_COUNT,
    RAG_FILE_MAX_SIZE,
    RAG_OPENAI_API_BASE_URL,
    RAG_OPENAI_API_KEY,
    RAG_OLLAMA_BASE_URL,
    RAG_OLLAMA_API_KEY,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    RAG_LATE_CHUNKING_ENABLED,
    QDRANT_URL,
    QDRANT_API_KEY,
    CLEANSING_ENABLED,
    CLEANSING_MODEL,
    SUMMARY_ENABLED,
    SUMMARY_MODEL,
    CONTENT_EXTRACTION_ENGINE,
    TIKA_SERVER_URL,
    DOCLING_SERVER_URL,
    DOCUMENT_INTELLIGENCE_ENDPOINT,
    DOCUMENT_INTELLIGENCE_KEY,
    RAG_TOP_K,
    RAG_TOP_K_RERANKER,
    RAG_TEXT_SPLITTER,
    TIKTOKEN_ENCODING_NAME,
    PDF_EXTRACT_IMAGES,
    YOUTUBE_LOADER_LANGUAGE,
    YOUTUBE_LOADER_PROXY_URL,
    # Retrieval — Web Search
    RAG_WEB_SEARCH_ENGINE,
    BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL,
    RAG_WEB_SEARCH_RESULT_COUNT,
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS,
    RAG_WEB_SEARCH_TRUST_ENV,
    RAG_WEB_SEARCH_DOMAIN_FILTER_LIST,
    RAG_WEB_SEARCH_QUERY_REWRITE_ENABLED,
    RAG_WEB_SEARCH_QUERY_REWRITE_MODEL,
    RAG_WEB_SEARCH_CONCURRENT_QUERIES,
    JINA_API_KEY,
    SEARCHAPI_API_KEY,
    SEARCHAPI_ENGINE,
    SERPAPI_API_KEY,
    SERPAPI_ENGINE,
    SEARXNG_QUERY_URL,
    SERPER_API_KEY,
    SERPLY_API_KEY,
    SERPSTACK_API_KEY,
    SERPSTACK_HTTPS,
    TAVILY_API_KEY,
    TAVILY_EXTRACT_DEPTH,
    BING_SEARCH_V7_ENDPOINT,
    BING_SEARCH_V7_SUBSCRIPTION_KEY,
    BRAVE_SEARCH_API_KEY,
    EXA_API_KEY,
    PERPLEXITY_API_KEY,
    KAGI_SEARCH_API_KEY,
    MOJEEK_SEARCH_API_KEY,
    BOCHA_SEARCH_API_KEY,
    NAVER_CLIENT_ID,
    NAVER_CLIENT_SECRET,
    NAVER_SEARCH_ENDPOINTS,
    GOOGLE_PSE_API_KEY,
    GOOGLE_PSE_ENGINE_ID,
    GOOGLE_DRIVE_CLIENT_ID,
    GOOGLE_DRIVE_API_KEY,
    ENABLE_RAG_HYBRID_SEARCH,
    ENABLE_RAG_LOCAL_WEB_FETCH,
    ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION,
    ENABLE_RAG_WEB_SEARCH,
    # Advanced RAG
    RAG_HYDE_ENABLED,
    RAG_HYDE_MODEL,
    RAG_QUERY_EXPANSION_ENABLED,
    RAG_QUERY_EXPANSION_MAX,
    RAG_STEP_BACK_ENABLED,
    RAG_RRF_K,
    RAG_RRF_VECTOR_WEIGHT,
    RAG_RRF_KEYWORD_WEIGHT,
    RAG_RULE_BASED_RERANKING_ENABLED,
    RAG_LLM_RERANKING_ENABLED,
    RAG_LLM_RERANKING_MODEL,
    RAG_CRAG_ENABLED,
    RAG_CRAG_THRESHOLD_SUFFICIENT,
    RAG_CRAG_THRESHOLD_INSUFFICIENT,
    RAG_DOC_GRADING_ENABLED,
    RAG_EVIDENCE_RECONCILIATION_ENABLED,
    # open-moai adoption — Phase 1
    CONTENT_ISOLATION_ENABLED,
    CONTENT_ISOLATION_METHOD,
    RAG_MMR_ENABLED,
    RAG_MMR_LAMBDA,
    QUERY_REWRITE_ENTITY_GUARD_ENABLED,
    AI_INTERACTION_AUDIT_ENABLED,
    FILE_MAGIC_VALIDATION_ENABLED,
    # open-moai adoption — Phase 2
    TOKEN_USAGE_PERSIST_ENABLED,
    TOKEN_BUDGET_ENABLED,
    TOKEN_BUDGET_DAILY,
    TOKEN_BUDGET_PER_MIN,
    RAG_CHUNK_QUALITY_ENABLED,
    RAG_COLUMN_PROFILER_ENABLED,
    CHAT_RETENTION_DAYS,
    CHAT_RETENTION_ANONYMIZE,
    MFA_ENABLED,
    MFA_REQUIRED_FOR_ADMIN,
    SCIM_ENABLED,
    SCIM_TOKEN,
    RAG_MULTI_HOP_ENABLED,
    RAG_MULTI_HOP_MAX_HOPS,
    RAG_MULTI_QUERY_WEIGHT_ORIGINAL,
    RAG_MULTI_QUERY_WEIGHT_EXPANDED,
    RAG_PARENT_CHILD_ENABLED,
    RAG_PARENT_CHILD_PARENT_SIZE,
    RAG_PARENT_CHILD_CHILD_SIZE,
    RAG_SEMANTIC_CACHE_ENABLED,
    RAG_SEMANTIC_CACHE_THRESHOLD,
    RAG_SEMANTIC_CACHE_TTL,
    RAG_CONTEXTUAL_RETRIEVAL_ENABLED,
    RAG_CONTEXTUAL_RETRIEVAL_MODEL,
    RAG_CONTEXTUAL_RETRIEVAL_MAX_CONTEXT_TOKENS,
    RAG_CONTEXTUAL_RETRIEVAL_BATCH_SIZE,
    RAG_CROSS_ENCODER_RERANKING_ENABLED,
    RAG_CROSS_ENCODER_MODEL,
    RAG_CROSS_ENCODER_MAX_LENGTH,
    RAG_CROSS_ENCODER_TOP_K,
    RAG_GRAPH_ENABLED,
    RAG_GRAPH_ENTITY_EXTRACTION_MODEL,
    RAG_GRAPH_MAX_ENTITIES,
    RAG_GRAPH_MAX_RELATIONS,
    RAG_GRAPH_COMMUNITY_DETECTION_ENABLED,
    RAG_GRAPH_MAX_HOPS,
    RAG_GRAPH_PPR_ENABLED,
    RAG_GRAPH_MIN_ENTITY_DOCS,
    RAG_EVALUATION_ENABLED,
    RAG_EVALUATION_MODEL,
    RAG_EVALUATION_METRICS,
    RAG_EVALUATION_LOG_RESULTS,
    ENABLE_GOOGLE_DRIVE_INTEGRATION,
    ENABLE_ONEDRIVE_INTEGRATION,
    UPLOAD_DIR,
    # WebUI
    BCGPT_AUTH,
    BCGPT_APP_NAME,
    BCGPT_BANNERS,
    WEBHOOK_URL,
    ADMIN_EMAIL,
    SHOW_ADMIN_DETAILS,
    JWT_EXPIRES_IN,
    ENABLE_SIGNUP,
    ENABLE_LOGIN_FORM,
    ENABLE_API_KEY,
    ENABLE_API_KEY_ENDPOINT_RESTRICTIONS,
    API_KEY_ALLOWED_ENDPOINTS,
    ENABLE_CHANNELS,
    ENABLE_COMMUNITY_SHARING,
    ENABLE_MESSAGE_RATING,
    ENABLE_USER_WEBHOOKS,
    ENABLE_EVALUATION_ARENA_MODELS,
    USER_PERMISSIONS,
    DEFAULT_USER_ROLE,
    DEFAULT_PROMPT_SUGGESTIONS,
    DEFAULT_MODELS,
    DEFAULT_ARENA_MODEL,
    MODEL_ORDER_LIST,
    EVALUATION_ARENA_MODELS,
    # WebUI — OAuth
    ENABLE_OAUTH_ROLE_MANAGEMENT,
    OAUTH_ROLES_CLAIM,
    OAUTH_EMAIL_CLAIM,
    OAUTH_PICTURE_CLAIM,
    OAUTH_USERNAME_CLAIM,
    OAUTH_ALLOWED_ROLES,
    OAUTH_ADMIN_ROLES,
    # WebUI — LDAP
    ENABLE_LDAP,
    LDAP_SERVER_LABEL,
    LDAP_SERVER_HOST,
    LDAP_SERVER_PORT,
    LDAP_ATTRIBUTE_FOR_MAIL,
    LDAP_ATTRIBUTE_FOR_USERNAME,
    LDAP_SEARCH_FILTERS,
    LDAP_SEARCH_BASE,
    LDAP_APP_DN,
    LDAP_APP_PASSWORD,
    LDAP_USE_TLS,
    LDAP_CA_CERT_FILE,
    LDAP_CIPHERS,
    # Misc
    ENV,
    CACHE_DIR,
    STATIC_DIR,
    FRONTEND_BUILD_DIR,
    CORS_ALLOW_ORIGIN,
    DEFAULT_LOCALE,
    OAUTH_PROVIDERS,
    BCGPT_URL,
    # Admin
    ENABLE_ADMIN_CHAT_ACCESS,
    ENABLE_ADMIN_EXPORT,
    # Tasks
    TASK_MODEL,
    TASK_MODEL_EXTERNAL,
    ENABLE_TAGS_GENERATION,
    ENABLE_TITLE_GENERATION,
    ENABLE_SEARCH_QUERY_GENERATION,
    ENABLE_RETRIEVAL_QUERY_GENERATION,
    ENABLE_AUTOCOMPLETE_GENERATION,
    TITLE_GENERATION_PROMPT_TEMPLATE,
    TAGS_GENERATION_PROMPT_TEMPLATE,
    IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE,
    IMAGE_PROMPT_TRANSLATION_TEMPLATE,
    IMAGE_PROMPT_EXPANSION_TEMPLATE,
    TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE,
    QUERY_GENERATION_PROMPT_TEMPLATE,
    AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE,
    AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH,
    ENABLE_CONTEXT_COMPRESSION,
    CONTEXT_COMPRESSION_MODEL,
    CONTEXT_COMPRESSION_PROMPT_TEMPLATE,
    ENABLE_SMART_QUERY,
    SMART_QUERY_MODEL,
    SMART_QUERY_PROMPT_TEMPLATE,
    # Security
    SECURITY_SCANNER_ENABLED,
    SECURITY_SHADOW_MODE,
    SECURITY_LOG_DETECTIONS,
    SECURITY_PROMPT_INJECTION_ENABLED,
    SECURITY_JAILBREAK_ENABLED,
    SECURITY_PII_ENABLED,
    SECURITY_PII_MASK_MODE,
    SECURITY_TOXICITY_ENABLED,
    SECURITY_TOXICITY_CUSTOM_WORD_LIST,
    SECURITY_SECRETS_ENABLED,
    SECURITY_OUTPUT_FILTER_ENABLED,
    SECURITY_EMERGENCY_STOP,
    SECURITY_CONVERSATION_SCANNING_ENABLED,
    SECURITY_CONVERSATION_THRESHOLD,
    SECURITY_CONFIDENCE_THRESHOLD,
    SECURITY_SCAN_FILE_UPLOADS,
    SECURITY_SCAN_WEB_RESULTS,
    SECURITY_LLM_SCANNER_ENABLED,
    SECURITY_LLM_SCANNER_MODEL,
    SECURITY_GUARDRAIL_ENABLED,
    SECURITY_GUARDRAIL_MODEL,
    SECURITY_GUARDRAIL_ACTION,
    SECURITY_CANARY_TOKENS_ENABLED,
    SECURITY_CANARY_TOKEN_POSITION,
    SECURITY_SIEM_WEBHOOK_ENABLED,
    SECURITY_SIEM_WEBHOOK_URL,
    SECURITY_SIEM_WEBHOOK_HEADERS,
    # AI Transparency
    AI_TRANSPARENCY_ENABLED,
    AI_NOTIFICATION_TITLE,
    AI_NOTIFICATION_MESSAGE,
    AI_DISCLAIMER_TEXT,
    AI_RESPONSE_LABEL,
    # LiteLLM Gateway
    LITELLM_GATEWAY_ENABLED,
    LITELLM_FALLBACK_MODEL,
    LITELLM_NUM_RETRIES,
    LITELLM_TIMEOUT,
    # Handoff
    HANDOFF_ENABLED,
    HANDOFF_EMAIL_ENABLED,
    HANDOFF_EMAIL_RECIPIENTS,
    HANDOFF_WEBHOOK_ENABLED,
    HANDOFF_WEBHOOK_URL,
    # Rate Limiting
    RATE_LIMIT_CHAT_ENABLED,
    RATE_LIMIT_CHAT_PER_MINUTE,
    RATE_LIMIT_CHAT_PER_HOUR,
    RATE_LIMIT_CHAT_PER_DAY,
    # LangFuse RAG Tracing
    RAG_TRACING_ENABLED,
    LANGFUSE_PUBLIC_KEY,
    LANGFUSE_SECRET_KEY,
    LANGFUSE_HOST,
    PROMETHEUS_METRICS_ENABLED,
    BCGPT_LOGO_URL,
    BCGPT_APP_NAME_PERSISTENT,
    COMPLIANCE_ENABLED,
    COMPLIANCE_INVENTORY_ENABLED,
    COMPLIANCE_AIIA_ENABLED,
    COMPLIANCE_HITL_ENABLED,
    COMPLIANCE_HITL_SLA_SECONDS,
    COMPLIANCE_INCIDENT_ENABLED,
    COMPLIANCE_FAIRNESS_ENABLED,
    COMPLIANCE_PROVENANCE_ENABLED,
    COMPLIANCE_DSAR_ENABLED,
    COMPLIANCE_VENDOR_ENABLED,
)

try:
    from bcgpt.config import (
        ENABLE_GEMINI_API,
        GEMINI_API_KEYS,
        GEMINI_API_BASE_URL,
        GEMINI_API_CONFIGS,
        ENABLE_CLAUDE_API,
        CLAUDE_API_KEYS,
        CLAUDE_API_BASE_URL,
        CLAUDE_API_CONFIGS,
    )
except ImportError:
    ENABLE_GEMINI_API = False
    GEMINI_API_KEYS = []
    GEMINI_API_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"
    GEMINI_API_CONFIGS = {}
    ENABLE_CLAUDE_API = False
    CLAUDE_API_KEYS = []
    CLAUDE_API_BASE_URL = "https://api.anthropic.com"
    CLAUDE_API_CONFIGS = {}

from bcgpt.env import (
    CHANGELOG,
    REDIS_URL,
    REDIS_SENTINEL_HOSTS,
    REDIS_SENTINEL_PORT,
    GLOBAL_LOG_LEVEL,
    MAX_BODY_LOG_SIZE,
    SAFE_MODE,
    SRC_LOG_LEVELS,
    VERSION,
    BCGPT_BUILD_HASH,
    BCGPT_SECRET_KEY,
    BCGPT_SESSION_COOKIE_SAME_SITE,
    BCGPT_SESSION_COOKIE_SECURE,
    BCGPT_AUTH_TRUSTED_EMAIL_HEADER,
    BCGPT_AUTH_TRUSTED_NAME_HEADER,
    ENABLE_WEBSOCKET_SUPPORT,
    BYPASS_MODEL_ACCESS_CONTROL,
    RESET_CONFIG_ON_START,
    OFFLINE_MODE,
    ENABLE_OTEL,
)

from bcgpt.tasks import (
    TaskNotFoundError,
    list_tasks,
    stop_generation,
    stop_task,
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(stream=sys.stdout, level=GLOBAL_LOG_LEVEL)
log = logging.getLogger(__name__)
log.setLevel(SRC_LOG_LEVELS["MAIN"])

if SAFE_MODE:
    print("SAFE MODE ENABLED")
    Functions.deactivate_all_functions()

print(rf"""
BCGPT
v{VERSION} - building the best open-source AI user interface.
{f"Commit: {BCGPT_BUILD_HASH}" if BCGPT_BUILD_HASH != "dev-build" else ""}
""")


# =========================================================================
# SPA fallback for static files
# =========================================================================


class SPAStaticFiles(StaticFiles):
    """Serves the frontend SPA — non-.js 404s fall back to index.html."""

    async def get_response(self, path: str, scope):
        try:
            return await super().get_response(path, scope)
        except (HTTPException, StarletteHTTPException) as ex:
            if ex.status_code == 404:
                if path.endswith(".js"):
                    raise ex
                return await super().get_response("index.html", scope)
            raise ex


# =========================================================================
# Middleware definitions
# =========================================================================


class RedirectMiddleware(BaseHTTPMiddleware):
    """Redirects legacy /watch?v=<id> URLs to /?youtube=<id>."""

    async def dispatch(self, request: Request, call_next):
        if request.method == "GET":
            path = request.url.path
            query_params = dict(parse_qs(urlparse(str(request.url)).query))
            if path.endswith("/watch") and "v" in query_params:
                video_id = query_params["v"][0]
                encoded = urlencode({"youtube": video_id})
                return RedirectResponse(url=f"/?{encoded}")
        return await call_next(request)


# =========================================================================
# Config application
# =========================================================================


def _apply_config(app: FastAPI) -> None:
    """Transfer all environment-derived config values into app.state.config."""

    cfg = app.state.config

    # ── LLM Providers ──────────────────────────────────────────────────
    cfg.ENABLE_OLLAMA_API = ENABLE_OLLAMA_API
    cfg.OLLAMA_BASE_URLS = OLLAMA_BASE_URLS
    cfg.OLLAMA_API_CONFIGS = OLLAMA_API_CONFIGS

    cfg.ENABLE_OPENAI_API = ENABLE_OPENAI_API
    cfg.OPENAI_API_BASE_URLS = OPENAI_API_BASE_URLS
    cfg.OPENAI_API_KEYS = OPENAI_API_KEYS
    cfg.OPENAI_API_CONFIGS = OPENAI_API_CONFIGS

    cfg.ENABLE_GEMINI_API = ENABLE_GEMINI_API
    cfg.GEMINI_API_KEYS = GEMINI_API_KEYS
    cfg.GEMINI_API_BASE_URL = GEMINI_API_BASE_URL
    cfg.GEMINI_API_CONFIGS = GEMINI_API_CONFIGS

    cfg.ENABLE_CLAUDE_API = ENABLE_CLAUDE_API
    cfg.CLAUDE_API_KEYS = CLAUDE_API_KEYS
    cfg.CLAUDE_API_BASE_URL = CLAUDE_API_BASE_URL
    cfg.CLAUDE_API_CONFIGS = CLAUDE_API_CONFIGS

    cfg.LITELLM_GATEWAY_ENABLED = LITELLM_GATEWAY_ENABLED
    cfg.LITELLM_FALLBACK_MODEL = LITELLM_FALLBACK_MODEL
    cfg.LITELLM_NUM_RETRIES = LITELLM_NUM_RETRIES
    cfg.LITELLM_TIMEOUT = LITELLM_TIMEOUT

    cfg.ENABLE_DIRECT_CONNECTIONS = ENABLE_DIRECT_CONNECTIONS
    cfg.ENABLE_MCP_SERVERS = ENABLE_MCP_SERVERS
    cfg.MCP_SERVERS = MCP_SERVERS
    cfg.MCP_ALLOWED_HOSTS = MCP_ALLOWED_HOSTS
    cfg.MCP_BUILTINS_ENABLED = MCP_BUILTINS_ENABLED

    # ── WebUI ──────────────────────────────────────────────────────────
    cfg.BCGPT_URL = BCGPT_URL
    cfg.BCGPT_LOGO_URL = BCGPT_LOGO_URL
    cfg.ENABLE_SIGNUP = ENABLE_SIGNUP
    cfg.ENABLE_LOGIN_FORM = ENABLE_LOGIN_FORM
    cfg.ENABLE_API_KEY = ENABLE_API_KEY
    cfg.ENABLE_API_KEY_ENDPOINT_RESTRICTIONS = ENABLE_API_KEY_ENDPOINT_RESTRICTIONS
    cfg.API_KEY_ALLOWED_ENDPOINTS = API_KEY_ALLOWED_ENDPOINTS
    cfg.JWT_EXPIRES_IN = JWT_EXPIRES_IN
    cfg.SHOW_ADMIN_DETAILS = SHOW_ADMIN_DETAILS
    cfg.ADMIN_EMAIL = ADMIN_EMAIL
    cfg.DEFAULT_MODELS = DEFAULT_MODELS
    cfg.DEFAULT_PROMPT_SUGGESTIONS = DEFAULT_PROMPT_SUGGESTIONS
    cfg.DEFAULT_USER_ROLE = DEFAULT_USER_ROLE
    cfg.USER_PERMISSIONS = USER_PERMISSIONS
    cfg.WEBHOOK_URL = WEBHOOK_URL
    cfg.BANNERS = BCGPT_BANNERS
    cfg.MODEL_ORDER_LIST = MODEL_ORDER_LIST

    cfg.ENABLE_CHANNELS = ENABLE_CHANNELS
    cfg.ENABLE_COMMUNITY_SHARING = ENABLE_COMMUNITY_SHARING
    cfg.ENABLE_MESSAGE_RATING = ENABLE_MESSAGE_RATING
    cfg.ENABLE_USER_WEBHOOKS = ENABLE_USER_WEBHOOKS
    cfg.ENABLE_EVALUATION_ARENA_MODELS = ENABLE_EVALUATION_ARENA_MODELS
    cfg.EVALUATION_ARENA_MODELS = EVALUATION_ARENA_MODELS

    # ── OAuth ──────────────────────────────────────────────────────────
    cfg.OAUTH_USERNAME_CLAIM = OAUTH_USERNAME_CLAIM
    cfg.OAUTH_PICTURE_CLAIM = OAUTH_PICTURE_CLAIM
    cfg.OAUTH_EMAIL_CLAIM = OAUTH_EMAIL_CLAIM
    cfg.ENABLE_OAUTH_ROLE_MANAGEMENT = ENABLE_OAUTH_ROLE_MANAGEMENT
    cfg.OAUTH_ROLES_CLAIM = OAUTH_ROLES_CLAIM
    cfg.OAUTH_ALLOWED_ROLES = OAUTH_ALLOWED_ROLES
    cfg.OAUTH_ADMIN_ROLES = OAUTH_ADMIN_ROLES

    # ── LDAP ───────────────────────────────────────────────────────────
    cfg.ENABLE_LDAP = ENABLE_LDAP
    cfg.LDAP_SERVER_LABEL = LDAP_SERVER_LABEL
    cfg.LDAP_SERVER_HOST = LDAP_SERVER_HOST
    cfg.LDAP_SERVER_PORT = LDAP_SERVER_PORT
    cfg.LDAP_ATTRIBUTE_FOR_MAIL = LDAP_ATTRIBUTE_FOR_MAIL
    cfg.LDAP_ATTRIBUTE_FOR_USERNAME = LDAP_ATTRIBUTE_FOR_USERNAME
    cfg.LDAP_APP_DN = LDAP_APP_DN
    cfg.LDAP_APP_PASSWORD = LDAP_APP_PASSWORD
    cfg.LDAP_SEARCH_BASE = LDAP_SEARCH_BASE
    cfg.LDAP_SEARCH_FILTERS = LDAP_SEARCH_FILTERS
    cfg.LDAP_USE_TLS = LDAP_USE_TLS
    cfg.LDAP_CA_CERT_FILE = LDAP_CA_CERT_FILE
    cfg.LDAP_CIPHERS = LDAP_CIPHERS

    # ── Retrieval ──────────────────────────────────────────────────────
    cfg.TOP_K = RAG_TOP_K
    cfg.TOP_K_RERANKER = RAG_TOP_K_RERANKER
    cfg.RELEVANCE_THRESHOLD = RAG_RELEVANCE_THRESHOLD
    cfg.FILE_MAX_SIZE = RAG_FILE_MAX_SIZE
    cfg.FILE_MAX_COUNT = RAG_FILE_MAX_COUNT
    cfg.RAG_FULL_CONTEXT = RAG_FULL_CONTEXT
    cfg.BYPASS_EMBEDDING_AND_RETRIEVAL = BYPASS_EMBEDDING_AND_RETRIEVAL
    cfg.ENABLE_RAG_HYBRID_SEARCH = ENABLE_RAG_HYBRID_SEARCH
    cfg.ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION = ENABLE_RAG_WEB_LOADER_SSL_VERIFICATION

    cfg.CONTENT_EXTRACTION_ENGINE = CONTENT_EXTRACTION_ENGINE
    cfg.TIKA_SERVER_URL = TIKA_SERVER_URL
    cfg.DOCLING_SERVER_URL = DOCLING_SERVER_URL
    cfg.DOCUMENT_INTELLIGENCE_ENDPOINT = DOCUMENT_INTELLIGENCE_ENDPOINT
    cfg.DOCUMENT_INTELLIGENCE_KEY = DOCUMENT_INTELLIGENCE_KEY

    cfg.TEXT_SPLITTER = RAG_TEXT_SPLITTER
    cfg.TIKTOKEN_ENCODING_NAME = TIKTOKEN_ENCODING_NAME
    cfg.CHUNK_SIZE = CHUNK_SIZE
    cfg.CHUNK_OVERLAP = CHUNK_OVERLAP
    cfg.RAG_LATE_CHUNKING_ENABLED = RAG_LATE_CHUNKING_ENABLED

    cfg.QDRANT_URL = QDRANT_URL
    cfg.QDRANT_API_KEY = QDRANT_API_KEY
    cfg.CLEANSING_ENABLED = CLEANSING_ENABLED
    cfg.CLEANSING_MODEL = CLEANSING_MODEL
    cfg.SUMMARY_ENABLED = SUMMARY_ENABLED
    cfg.SUMMARY_MODEL = SUMMARY_MODEL

    cfg.RAG_EMBEDDING_ENGINE = RAG_EMBEDDING_ENGINE
    cfg.RAG_EMBEDDING_MODEL = RAG_EMBEDDING_MODEL
    cfg.RAG_EMBEDDING_BATCH_SIZE = RAG_EMBEDDING_BATCH_SIZE
    cfg.RAG_EMBEDDING_MODEL_URI = RAG_EMBEDDING_MODEL_URI
    cfg.RAG_EMBEDDING_MODEL_API_KEY = RAG_EMBEDDING_MODEL_API_KEY
    cfg.RAG_RERANKING_MODEL = RAG_RERANKING_MODEL
    cfg.RAG_RERANKING_MODEL_URI = RAG_RERANKING_MODEL_URI
    cfg.RAG_RERANKING_MODEL_API_KEY = RAG_RERANKING_MODEL_API_KEY
    cfg.RAG_TEMPLATE = RAG_TEMPLATE

    cfg.RAG_HYDE_ENABLED = RAG_HYDE_ENABLED
    cfg.RAG_HYDE_MODEL = RAG_HYDE_MODEL
    cfg.RAG_QUERY_EXPANSION_ENABLED = RAG_QUERY_EXPANSION_ENABLED
    cfg.RAG_QUERY_EXPANSION_MAX = RAG_QUERY_EXPANSION_MAX
    cfg.RAG_STEP_BACK_ENABLED = RAG_STEP_BACK_ENABLED
    cfg.RAG_RRF_K = RAG_RRF_K
    cfg.RAG_RRF_VECTOR_WEIGHT = RAG_RRF_VECTOR_WEIGHT
    cfg.RAG_RRF_KEYWORD_WEIGHT = RAG_RRF_KEYWORD_WEIGHT
    cfg.RAG_RULE_BASED_RERANKING_ENABLED = RAG_RULE_BASED_RERANKING_ENABLED
    cfg.RAG_LLM_RERANKING_ENABLED = RAG_LLM_RERANKING_ENABLED
    cfg.RAG_LLM_RERANKING_MODEL = RAG_LLM_RERANKING_MODEL
    cfg.RAG_CRAG_ENABLED = RAG_CRAG_ENABLED
    cfg.RAG_CRAG_THRESHOLD_SUFFICIENT = RAG_CRAG_THRESHOLD_SUFFICIENT
    cfg.RAG_CRAG_THRESHOLD_INSUFFICIENT = RAG_CRAG_THRESHOLD_INSUFFICIENT
    cfg.RAG_DOC_GRADING_ENABLED = RAG_DOC_GRADING_ENABLED
    cfg.RAG_EVIDENCE_RECONCILIATION_ENABLED = RAG_EVIDENCE_RECONCILIATION_ENABLED
    cfg.RAG_MULTI_HOP_ENABLED = RAG_MULTI_HOP_ENABLED
    cfg.RAG_MULTI_HOP_MAX_HOPS = RAG_MULTI_HOP_MAX_HOPS
    cfg.RAG_MULTI_QUERY_WEIGHT_ORIGINAL = RAG_MULTI_QUERY_WEIGHT_ORIGINAL
    cfg.RAG_MULTI_QUERY_WEIGHT_EXPANDED = RAG_MULTI_QUERY_WEIGHT_EXPANDED
    cfg.RAG_PARENT_CHILD_ENABLED = RAG_PARENT_CHILD_ENABLED
    cfg.RAG_PARENT_CHILD_PARENT_SIZE = RAG_PARENT_CHILD_PARENT_SIZE
    cfg.RAG_PARENT_CHILD_CHILD_SIZE = RAG_PARENT_CHILD_CHILD_SIZE
    cfg.RAG_SEMANTIC_CACHE_ENABLED = RAG_SEMANTIC_CACHE_ENABLED
    cfg.RAG_SEMANTIC_CACHE_THRESHOLD = RAG_SEMANTIC_CACHE_THRESHOLD
    cfg.RAG_SEMANTIC_CACHE_TTL = RAG_SEMANTIC_CACHE_TTL

    cfg.RAG_CONTEXTUAL_RETRIEVAL_ENABLED = RAG_CONTEXTUAL_RETRIEVAL_ENABLED
    cfg.RAG_CONTEXTUAL_RETRIEVAL_MODEL = RAG_CONTEXTUAL_RETRIEVAL_MODEL
    cfg.RAG_CONTEXTUAL_RETRIEVAL_MAX_CONTEXT_TOKENS = (
        RAG_CONTEXTUAL_RETRIEVAL_MAX_CONTEXT_TOKENS
    )
    cfg.RAG_CONTEXTUAL_RETRIEVAL_BATCH_SIZE = RAG_CONTEXTUAL_RETRIEVAL_BATCH_SIZE

    cfg.RAG_CROSS_ENCODER_RERANKING_ENABLED = RAG_CROSS_ENCODER_RERANKING_ENABLED
    cfg.RAG_CROSS_ENCODER_MODEL = RAG_CROSS_ENCODER_MODEL
    cfg.RAG_CROSS_ENCODER_MAX_LENGTH = RAG_CROSS_ENCODER_MAX_LENGTH
    cfg.RAG_CROSS_ENCODER_TOP_K = RAG_CROSS_ENCODER_TOP_K

    cfg.RAG_GRAPH_ENABLED = RAG_GRAPH_ENABLED
    cfg.RAG_GRAPH_ENTITY_EXTRACTION_MODEL = RAG_GRAPH_ENTITY_EXTRACTION_MODEL
    cfg.RAG_GRAPH_MAX_ENTITIES = RAG_GRAPH_MAX_ENTITIES
    cfg.RAG_GRAPH_MAX_RELATIONS = RAG_GRAPH_MAX_RELATIONS
    cfg.RAG_GRAPH_COMMUNITY_DETECTION_ENABLED = RAG_GRAPH_COMMUNITY_DETECTION_ENABLED
    cfg.RAG_GRAPH_MAX_HOPS = RAG_GRAPH_MAX_HOPS
    cfg.RAG_GRAPH_PPR_ENABLED = RAG_GRAPH_PPR_ENABLED
    cfg.RAG_GRAPH_MIN_ENTITY_DOCS = RAG_GRAPH_MIN_ENTITY_DOCS

    cfg.RAG_EVALUATION_ENABLED = RAG_EVALUATION_ENABLED
    cfg.RAG_EVALUATION_MODEL = RAG_EVALUATION_MODEL
    cfg.RAG_EVALUATION_METRICS = RAG_EVALUATION_METRICS
    cfg.RAG_EVALUATION_LOG_RESULTS = RAG_EVALUATION_LOG_RESULTS

    cfg.RAG_OPENAI_API_BASE_URL = RAG_OPENAI_API_BASE_URL
    cfg.RAG_OPENAI_API_KEY = RAG_OPENAI_API_KEY
    cfg.RAG_OLLAMA_BASE_URL = RAG_OLLAMA_BASE_URL
    cfg.RAG_OLLAMA_API_KEY = RAG_OLLAMA_API_KEY
    cfg.PDF_EXTRACT_IMAGES = PDF_EXTRACT_IMAGES
    cfg.YOUTUBE_LOADER_LANGUAGE = YOUTUBE_LOADER_LANGUAGE
    cfg.YOUTUBE_LOADER_PROXY_URL = YOUTUBE_LOADER_PROXY_URL

    # ── open-moai adoption — Phase 1 ───────────────────────────────────
    cfg.CONTENT_ISOLATION_ENABLED = CONTENT_ISOLATION_ENABLED
    cfg.CONTENT_ISOLATION_METHOD = CONTENT_ISOLATION_METHOD
    cfg.RAG_MMR_ENABLED = RAG_MMR_ENABLED
    cfg.RAG_MMR_LAMBDA = RAG_MMR_LAMBDA
    cfg.QUERY_REWRITE_ENTITY_GUARD_ENABLED = QUERY_REWRITE_ENTITY_GUARD_ENABLED
    cfg.AI_INTERACTION_AUDIT_ENABLED = AI_INTERACTION_AUDIT_ENABLED
    cfg.FILE_MAGIC_VALIDATION_ENABLED = FILE_MAGIC_VALIDATION_ENABLED

    # ── open-moai adoption — Phase 2 ───────────────────────────────────
    cfg.TOKEN_USAGE_PERSIST_ENABLED = TOKEN_USAGE_PERSIST_ENABLED
    cfg.TOKEN_BUDGET_ENABLED = TOKEN_BUDGET_ENABLED
    cfg.TOKEN_BUDGET_DAILY = TOKEN_BUDGET_DAILY
    cfg.TOKEN_BUDGET_PER_MIN = TOKEN_BUDGET_PER_MIN
    cfg.RAG_CHUNK_QUALITY_ENABLED = RAG_CHUNK_QUALITY_ENABLED
    cfg.RAG_COLUMN_PROFILER_ENABLED = RAG_COLUMN_PROFILER_ENABLED
    cfg.CHAT_RETENTION_DAYS = CHAT_RETENTION_DAYS
    cfg.CHAT_RETENTION_ANONYMIZE = CHAT_RETENTION_ANONYMIZE
    cfg.MFA_ENABLED = MFA_ENABLED
    cfg.MFA_REQUIRED_FOR_ADMIN = MFA_REQUIRED_FOR_ADMIN
    cfg.SCIM_ENABLED = SCIM_ENABLED
    cfg.SCIM_TOKEN = SCIM_TOKEN

    # ── Web Search ─────────────────────────────────────────────────────
    cfg.ENABLE_RAG_WEB_SEARCH = ENABLE_RAG_WEB_SEARCH
    cfg.RAG_WEB_SEARCH_ENGINE = RAG_WEB_SEARCH_ENGINE
    cfg.BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL = (
        BYPASS_WEB_SEARCH_EMBEDDING_AND_RETRIEVAL
    )
    cfg.RAG_WEB_SEARCH_DOMAIN_FILTER_LIST = RAG_WEB_SEARCH_DOMAIN_FILTER_LIST
    cfg.RAG_WEB_SEARCH_QUERY_REWRITE_ENABLED = RAG_WEB_SEARCH_QUERY_REWRITE_ENABLED
    cfg.RAG_WEB_SEARCH_QUERY_REWRITE_MODEL = RAG_WEB_SEARCH_QUERY_REWRITE_MODEL
    cfg.RAG_WEB_SEARCH_CONCURRENT_QUERIES = RAG_WEB_SEARCH_CONCURRENT_QUERIES

    cfg.ENABLE_GOOGLE_DRIVE_INTEGRATION = ENABLE_GOOGLE_DRIVE_INTEGRATION
    cfg.ENABLE_ONEDRIVE_INTEGRATION = ENABLE_ONEDRIVE_INTEGRATION

    cfg.SEARXNG_QUERY_URL = SEARXNG_QUERY_URL
    cfg.GOOGLE_PSE_API_KEY = GOOGLE_PSE_API_KEY
    cfg.GOOGLE_PSE_ENGINE_ID = GOOGLE_PSE_ENGINE_ID
    cfg.BRAVE_SEARCH_API_KEY = BRAVE_SEARCH_API_KEY
    cfg.KAGI_SEARCH_API_KEY = KAGI_SEARCH_API_KEY
    cfg.MOJEEK_SEARCH_API_KEY = MOJEEK_SEARCH_API_KEY
    cfg.BOCHA_SEARCH_API_KEY = BOCHA_SEARCH_API_KEY
    cfg.NAVER_CLIENT_ID = NAVER_CLIENT_ID
    cfg.NAVER_CLIENT_SECRET = NAVER_CLIENT_SECRET
    cfg.NAVER_SEARCH_ENDPOINTS = NAVER_SEARCH_ENDPOINTS
    cfg.SERPSTACK_API_KEY = SERPSTACK_API_KEY
    cfg.SERPSTACK_HTTPS = SERPSTACK_HTTPS
    cfg.SERPER_API_KEY = SERPER_API_KEY
    cfg.SERPLY_API_KEY = SERPLY_API_KEY
    cfg.TAVILY_API_KEY = TAVILY_API_KEY
    cfg.SEARCHAPI_API_KEY = SEARCHAPI_API_KEY
    cfg.SEARCHAPI_ENGINE = SEARCHAPI_ENGINE
    cfg.SERPAPI_API_KEY = SERPAPI_API_KEY
    cfg.SERPAPI_ENGINE = SERPAPI_ENGINE
    cfg.JINA_API_KEY = JINA_API_KEY
    cfg.BING_SEARCH_V7_ENDPOINT = BING_SEARCH_V7_ENDPOINT
    cfg.BING_SEARCH_V7_SUBSCRIPTION_KEY = BING_SEARCH_V7_SUBSCRIPTION_KEY
    cfg.EXA_API_KEY = EXA_API_KEY
    cfg.PERPLEXITY_API_KEY = PERPLEXITY_API_KEY

    cfg.RAG_WEB_SEARCH_RESULT_COUNT = RAG_WEB_SEARCH_RESULT_COUNT
    cfg.RAG_WEB_SEARCH_CONCURRENT_REQUESTS = RAG_WEB_SEARCH_CONCURRENT_REQUESTS
    cfg.RAG_WEB_LOADER_ENGINE = RAG_WEB_LOADER_ENGINE
    cfg.RAG_WEB_SEARCH_TRUST_ENV = RAG_WEB_SEARCH_TRUST_ENV
    cfg.PLAYWRIGHT_WS_URI = PLAYWRIGHT_WS_URI
    cfg.PLAYWRIGHT_TIMEOUT = PLAYWRIGHT_TIMEOUT
    cfg.FIRECRAWL_API_BASE_URL = FIRECRAWL_API_BASE_URL
    cfg.FIRECRAWL_API_KEY = FIRECRAWL_API_KEY
    cfg.TAVILY_EXTRACT_DEPTH = TAVILY_EXTRACT_DEPTH

    # ── Images ─────────────────────────────────────────────────────────
    cfg.IMAGE_GENERATION_ENGINE = IMAGE_GENERATION_ENGINE
    cfg.ENABLE_IMAGE_GENERATION = ENABLE_IMAGE_GENERATION
    cfg.ENABLE_IMAGE_PROMPT_GENERATION = ENABLE_IMAGE_PROMPT_GENERATION
    cfg.ENABLE_IMAGE_PROMPT_TRANSLATION = ENABLE_IMAGE_PROMPT_TRANSLATION
    cfg.ENABLE_IMAGE_PROMPT_EXPANSION = ENABLE_IMAGE_PROMPT_EXPANSION
    cfg.IMAGES_OPENAI_API_BASE_URL = IMAGES_OPENAI_API_BASE_URL
    cfg.IMAGES_OPENAI_API_KEY = IMAGES_OPENAI_API_KEY
    cfg.IMAGES_GEMINI_API_BASE_URL = IMAGES_GEMINI_API_BASE_URL
    cfg.IMAGES_GEMINI_API_KEY = IMAGES_GEMINI_API_KEY
    cfg.IMAGE_GENERATION_MODEL = IMAGE_GENERATION_MODEL
    cfg.AUTOMATIC1111_BASE_URL = AUTOMATIC1111_BASE_URL
    cfg.AUTOMATIC1111_API_AUTH = AUTOMATIC1111_API_AUTH
    cfg.AUTOMATIC1111_CFG_SCALE = AUTOMATIC1111_CFG_SCALE
    cfg.AUTOMATIC1111_SAMPLER = AUTOMATIC1111_SAMPLER
    cfg.AUTOMATIC1111_SCHEDULER = AUTOMATIC1111_SCHEDULER
    cfg.COMFYUI_BASE_URL = COMFYUI_BASE_URL
    cfg.COMFYUI_API_KEY = COMFYUI_API_KEY
    cfg.COMFYUI_WORKFLOW = COMFYUI_WORKFLOW
    cfg.COMFYUI_WORKFLOW_NODES = COMFYUI_WORKFLOW_NODES
    cfg.IMAGE_SIZE = IMAGE_SIZE
    cfg.IMAGE_STEPS = IMAGE_STEPS

    # ── Audio ──────────────────────────────────────────────────────────
    cfg.STT_OPENAI_API_BASE_URL = AUDIO_STT_OPENAI_API_BASE_URL
    cfg.STT_OPENAI_API_KEY = AUDIO_STT_OPENAI_API_KEY
    cfg.STT_ENGINE = AUDIO_STT_ENGINE
    cfg.STT_MODEL = AUDIO_STT_MODEL
    cfg.DEEPGRAM_API_KEY = DEEPGRAM_API_KEY
    cfg.TTS_OPENAI_API_BASE_URL = AUDIO_TTS_OPENAI_API_BASE_URL
    cfg.TTS_OPENAI_API_KEY = AUDIO_TTS_OPENAI_API_KEY
    cfg.TTS_ENGINE = AUDIO_TTS_ENGINE
    cfg.TTS_MODEL = AUDIO_TTS_MODEL
    cfg.TTS_VOICE = AUDIO_TTS_VOICE
    cfg.TTS_API_KEY = AUDIO_TTS_API_KEY
    cfg.TTS_SPLIT_ON = AUDIO_TTS_SPLIT_ON
    cfg.TTS_AZURE_SPEECH_REGION = AUDIO_TTS_AZURE_SPEECH_REGION
    cfg.TTS_AZURE_SPEECH_OUTPUT_FORMAT = AUDIO_TTS_AZURE_SPEECH_OUTPUT_FORMAT

    # ── Tasks ──────────────────────────────────────────────────────────
    cfg.TASK_MODEL = TASK_MODEL
    cfg.TASK_MODEL_EXTERNAL = TASK_MODEL_EXTERNAL
    cfg.ENABLE_SEARCH_QUERY_GENERATION = ENABLE_SEARCH_QUERY_GENERATION
    cfg.ENABLE_RETRIEVAL_QUERY_GENERATION = ENABLE_RETRIEVAL_QUERY_GENERATION
    cfg.ENABLE_AUTOCOMPLETE_GENERATION = ENABLE_AUTOCOMPLETE_GENERATION
    cfg.ENABLE_TAGS_GENERATION = ENABLE_TAGS_GENERATION
    cfg.ENABLE_TITLE_GENERATION = ENABLE_TITLE_GENERATION
    cfg.TITLE_GENERATION_PROMPT_TEMPLATE = TITLE_GENERATION_PROMPT_TEMPLATE
    cfg.TAGS_GENERATION_PROMPT_TEMPLATE = TAGS_GENERATION_PROMPT_TEMPLATE
    cfg.IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE = (
        IMAGE_PROMPT_GENERATION_PROMPT_TEMPLATE
    )
    cfg.IMAGE_PROMPT_TRANSLATION_TEMPLATE = IMAGE_PROMPT_TRANSLATION_TEMPLATE
    cfg.IMAGE_PROMPT_EXPANSION_TEMPLATE = IMAGE_PROMPT_EXPANSION_TEMPLATE
    cfg.TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE = TOOLS_FUNCTION_CALLING_PROMPT_TEMPLATE
    cfg.QUERY_GENERATION_PROMPT_TEMPLATE = QUERY_GENERATION_PROMPT_TEMPLATE
    cfg.AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE = (
        AUTOCOMPLETE_GENERATION_PROMPT_TEMPLATE
    )
    cfg.AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH = (
        AUTOCOMPLETE_GENERATION_INPUT_MAX_LENGTH
    )

    cfg.ENABLE_CONTEXT_COMPRESSION = ENABLE_CONTEXT_COMPRESSION
    cfg.CONTEXT_COMPRESSION_MODEL = CONTEXT_COMPRESSION_MODEL
    cfg.CONTEXT_COMPRESSION_PROMPT_TEMPLATE = CONTEXT_COMPRESSION_PROMPT_TEMPLATE

    cfg.ENABLE_SMART_QUERY = ENABLE_SMART_QUERY
    cfg.SMART_QUERY_MODEL = SMART_QUERY_MODEL
    cfg.SMART_QUERY_PROMPT_TEMPLATE = SMART_QUERY_PROMPT_TEMPLATE

    # ── Security ───────────────────────────────────────────────────────
    cfg.SECURITY_SCANNER_ENABLED = SECURITY_SCANNER_ENABLED
    cfg.SECURITY_SHADOW_MODE = SECURITY_SHADOW_MODE
    cfg.SECURITY_LOG_DETECTIONS = SECURITY_LOG_DETECTIONS
    cfg.SECURITY_PROMPT_INJECTION_ENABLED = SECURITY_PROMPT_INJECTION_ENABLED
    cfg.SECURITY_JAILBREAK_ENABLED = SECURITY_JAILBREAK_ENABLED
    cfg.SECURITY_PII_ENABLED = SECURITY_PII_ENABLED
    cfg.SECURITY_PII_MASK_MODE = SECURITY_PII_MASK_MODE
    cfg.SECURITY_TOXICITY_ENABLED = SECURITY_TOXICITY_ENABLED
    cfg.SECURITY_TOXICITY_CUSTOM_WORD_LIST = SECURITY_TOXICITY_CUSTOM_WORD_LIST
    cfg.SECURITY_SECRETS_ENABLED = SECURITY_SECRETS_ENABLED
    cfg.SECURITY_OUTPUT_FILTER_ENABLED = SECURITY_OUTPUT_FILTER_ENABLED
    cfg.SECURITY_EMERGENCY_STOP = SECURITY_EMERGENCY_STOP
    cfg.SECURITY_CONVERSATION_SCANNING_ENABLED = SECURITY_CONVERSATION_SCANNING_ENABLED
    cfg.SECURITY_CONVERSATION_THRESHOLD = SECURITY_CONVERSATION_THRESHOLD
    cfg.SECURITY_CONFIDENCE_THRESHOLD = SECURITY_CONFIDENCE_THRESHOLD
    cfg.SECURITY_SCAN_FILE_UPLOADS = SECURITY_SCAN_FILE_UPLOADS
    cfg.SECURITY_SCAN_WEB_RESULTS = SECURITY_SCAN_WEB_RESULTS
    cfg.SECURITY_LLM_SCANNER_ENABLED = SECURITY_LLM_SCANNER_ENABLED
    cfg.SECURITY_LLM_SCANNER_MODEL = SECURITY_LLM_SCANNER_MODEL
    cfg.SECURITY_GUARDRAIL_ENABLED = SECURITY_GUARDRAIL_ENABLED
    cfg.SECURITY_GUARDRAIL_MODEL = SECURITY_GUARDRAIL_MODEL
    cfg.SECURITY_GUARDRAIL_ACTION = SECURITY_GUARDRAIL_ACTION
    cfg.SECURITY_CANARY_TOKENS_ENABLED = SECURITY_CANARY_TOKENS_ENABLED
    cfg.SECURITY_CANARY_TOKEN_POSITION = SECURITY_CANARY_TOKEN_POSITION
    cfg.SECURITY_SIEM_WEBHOOK_ENABLED = SECURITY_SIEM_WEBHOOK_ENABLED
    cfg.SECURITY_SIEM_WEBHOOK_URL = SECURITY_SIEM_WEBHOOK_URL
    cfg.SECURITY_SIEM_WEBHOOK_HEADERS = SECURITY_SIEM_WEBHOOK_HEADERS

    # ── AI Transparency ────────────────────────────────────────────────
    cfg.AI_TRANSPARENCY_ENABLED = AI_TRANSPARENCY_ENABLED
    cfg.AI_NOTIFICATION_TITLE = AI_NOTIFICATION_TITLE
    cfg.AI_NOTIFICATION_MESSAGE = AI_NOTIFICATION_MESSAGE
    cfg.AI_DISCLAIMER_TEXT = AI_DISCLAIMER_TEXT
    cfg.AI_RESPONSE_LABEL = AI_RESPONSE_LABEL

    # ── Handoff ────────────────────────────────────────────────────────
    cfg.HANDOFF_ENABLED = HANDOFF_ENABLED
    cfg.HANDOFF_EMAIL_ENABLED = HANDOFF_EMAIL_ENABLED
    cfg.HANDOFF_EMAIL_RECIPIENTS = HANDOFF_EMAIL_RECIPIENTS
    cfg.HANDOFF_WEBHOOK_ENABLED = HANDOFF_WEBHOOK_ENABLED
    cfg.HANDOFF_WEBHOOK_URL = HANDOFF_WEBHOOK_URL

    # ── Rate Limiting ──────────────────────────────────────────────────
    cfg.RATE_LIMIT_CHAT_ENABLED = RATE_LIMIT_CHAT_ENABLED
    cfg.RATE_LIMIT_CHAT_PER_MINUTE = RATE_LIMIT_CHAT_PER_MINUTE
    cfg.RATE_LIMIT_CHAT_PER_HOUR = RATE_LIMIT_CHAT_PER_HOUR
    cfg.RATE_LIMIT_CHAT_PER_DAY = RATE_LIMIT_CHAT_PER_DAY

    # ── LangFuse Tracing ───────────────────────────────────────────────
    cfg.RAG_TRACING_ENABLED = RAG_TRACING_ENABLED
    cfg.LANGFUSE_PUBLIC_KEY = LANGFUSE_PUBLIC_KEY
    cfg.LANGFUSE_SECRET_KEY = LANGFUSE_SECRET_KEY
    cfg.LANGFUSE_HOST = LANGFUSE_HOST

    # ── AI Compliance ──────────────────────────────────────────────────
    cfg.COMPLIANCE_ENABLED = COMPLIANCE_ENABLED
    cfg.COMPLIANCE_INVENTORY_ENABLED = COMPLIANCE_INVENTORY_ENABLED
    cfg.COMPLIANCE_AIIA_ENABLED = COMPLIANCE_AIIA_ENABLED
    cfg.COMPLIANCE_HITL_ENABLED = COMPLIANCE_HITL_ENABLED
    cfg.COMPLIANCE_HITL_SLA_SECONDS = COMPLIANCE_HITL_SLA_SECONDS
    from bcgpt.compliance.hitl import ApprovalGates

    ApprovalGates.configure(
        enabled=bool(COMPLIANCE_HITL_ENABLED.value),
        sla_seconds=int(COMPLIANCE_HITL_SLA_SECONDS.value),
    )
    cfg.COMPLIANCE_INCIDENT_ENABLED = COMPLIANCE_INCIDENT_ENABLED
    cfg.COMPLIANCE_FAIRNESS_ENABLED = COMPLIANCE_FAIRNESS_ENABLED
    cfg.COMPLIANCE_PROVENANCE_ENABLED = COMPLIANCE_PROVENANCE_ENABLED
    cfg.COMPLIANCE_DSAR_ENABLED = COMPLIANCE_DSAR_ENABLED
    cfg.COMPLIANCE_VENDOR_ENABLED = COMPLIANCE_VENDOR_ENABLED

    # ── Audit ──────────────────────────────────────────────────────────
    cfg.AUDIT_LOG_LEVEL = AUDIT_LOG_LEVEL
    cfg.AUDIT_EXCLUDED_PATHS = AUDIT_EXCLUDED_PATHS
    cfg.MAX_BODY_LOG_SIZE = AUDIT_MAX_BODY_LOG_SIZE
    cfg.AUDIT_LOG_FILE_ROTATION_SIZE = AUDIT_LOG_FILE_ROTATION_SIZE
    cfg.AUDIT_RETENTION_DAYS = AUDIT_RETENTION_DAYS

    # ── Agent subsystem ────────────────────────────────────────────────
    cfg.AGENT_DEFAULT_AUTONOMY_LEVEL = AGENT_DEFAULT_AUTONOMY_LEVEL
    cfg.AGENT_OPERATOR_MAX_TOOL_ITERATIONS = AGENT_OPERATOR_MAX_TOOL_ITERATIONS
    cfg.AGENT_QUALITY_PIPELINE_ENABLED = AGENT_QUALITY_PIPELINE_ENABLED
    cfg.AGENT_QUALITY_SAMPLING_RATE = AGENT_QUALITY_SAMPLING_RATE
    cfg.WORKFLOW_ENGINE_ENABLED = WORKFLOW_ENGINE_ENABLED
    cfg.WORKFLOW_DEFAULT_TIMEOUT = WORKFLOW_DEFAULT_TIMEOUT
    cfg.WORKFLOW_NODE_TIMEOUT = WORKFLOW_NODE_TIMEOUT
    cfg.MULTI_AGENT_ENABLED = MULTI_AGENT_ENABLED
    cfg.MULTI_AGENT_MAX_PARALLEL = MULTI_AGENT_MAX_PARALLEL
    cfg.MULTI_AGENT_DEBATE_ROUNDS = MULTI_AGENT_DEBATE_ROUNDS
    cfg.MULTI_AGENT_CONSENSUS_THRESHOLD = MULTI_AGENT_CONSENSUS_THRESHOLD
    cfg.QUALITY_CLAIM_DECOMPOSITION_ENABLED = QUALITY_CLAIM_DECOMPOSITION_ENABLED
    cfg.QUALITY_GROUNDING_ENABLED = QUALITY_GROUNDING_ENABLED
    cfg.QUALITY_DOC_GRADING_ENABLED = QUALITY_DOC_GRADING_ENABLED
    cfg.QUALITY_CLAIM_MODEL = QUALITY_CLAIM_MODEL
    cfg.QUALITY_GROUNDING_MODEL = QUALITY_GROUNDING_MODEL
    cfg.QUALITY_DOC_GRADING_MODEL = QUALITY_DOC_GRADING_MODEL
    cfg.QUALITY_ENTAILMENT_MODEL = QUALITY_ENTAILMENT_MODEL
    cfg.QUALITY_DEFAULT_MODEL = QUALITY_DEFAULT_MODEL
    cfg.LETTUCE_DETECT_ENABLED = LETTUCE_DETECT_ENABLED
    cfg.LETTUCE_DETECT_THRESHOLD = LETTUCE_DETECT_THRESHOLD

    # ── Non-config app state ───────────────────────────────────────────
    app.state.BCGPT_APP_NAME = BCGPT_APP_NAME_PERSISTENT.value
    app.state.LICENSE_METADATA = None
    app.state.AUTH_TRUSTED_EMAIL_HEADER = BCGPT_AUTH_TRUSTED_EMAIL_HEADER
    app.state.AUTH_TRUSTED_NAME_HEADER = BCGPT_AUTH_TRUSTED_NAME_HEADER
    app.state.USER_COUNT = None
    app.state.TOOLS = {}
    app.state.FUNCTIONS = {}
    app.state.MODELS = {}

    app.state.OLLAMA_MODELS = {}
    app.state.OPENAI_MODELS = {}
    app.state.GEMINI_MODELS = {}
    app.state.CLAUDE_MODELS = {}
    app.state.EMBEDDING_FUNCTION = None
    app.state.ef = None
    app.state.rf = None
    app.state.YOUTUBE_LOADER_TRANSLATION = None


# =========================================================================
# Embedding function initialisation
# =========================================================================


def _init_embeddings(app: FastAPI) -> None:
    """Set up the embedding function and reranking model."""
    cfg = app.state.config

    try:
        if cfg.RAG_EMBEDDING_MODEL_URI:
            app.state.ef = None
        else:
            app.state.ef = get_ef(
                cfg.RAG_EMBEDDING_ENGINE,
                cfg.RAG_EMBEDDING_MODEL,
                RAG_EMBEDDING_MODEL_AUTO_UPDATE,
            )

        app.state.rf = get_rf(
            cfg.RAG_RERANKING_MODEL,
            RAG_RERANKING_MODEL_AUTO_UPDATE,
            uri=cfg.RAG_RERANKING_MODEL_URI,
            api_key=cfg.RAG_RERANKING_MODEL_API_KEY,
        )
    except Exception as e:
        log.error(f"Error updating models: {e}")

    if cfg.RAG_EMBEDDING_MODEL_URI:
        app.state.EMBEDDING_FUNCTION = get_embedding_function(
            "openai",
            cfg.RAG_EMBEDDING_MODEL,
            None,
            cfg.RAG_EMBEDDING_MODEL_URI,
            cfg.RAG_EMBEDDING_MODEL_API_KEY,
            cfg.RAG_EMBEDDING_BATCH_SIZE,
        )
        if app.state.EMBEDDING_FUNCTION is None:
            log.warning(
                "Embedding function could not be created for URI-based model. "
                "Vector DB features will be unavailable."
            )
    else:
        if app.state.ef is None and cfg.RAG_EMBEDDING_ENGINE == "":
            log.warning(
                "Local embedding model failed to load. "
                "Vector DB features will be unavailable until the model is configured."
            )
            app.state.EMBEDDING_FUNCTION = None
        else:
            api_url = (
                cfg.RAG_OPENAI_API_BASE_URL
                if cfg.RAG_EMBEDDING_ENGINE == "openai"
                else cfg.RAG_OLLAMA_BASE_URL
            )
            api_key = (
                cfg.RAG_OPENAI_API_KEY
                if cfg.RAG_EMBEDDING_ENGINE == "openai"
                else cfg.RAG_OLLAMA_API_KEY
            )
            app.state.EMBEDDING_FUNCTION = get_embedding_function(
                cfg.RAG_EMBEDDING_ENGINE,
                cfg.RAG_EMBEDDING_MODEL,
                app.state.ef,
                api_url,
                api_key,
                cfg.RAG_EMBEDDING_BATCH_SIZE,
            )


# =========================================================================
# Middleware setup
# =========================================================================


def _setup_middleware(app: FastAPI) -> None:
    """Register the full middleware chain."""

    # Class-based middleware (added in LIFO order — last added runs first)
    app.add_middleware(RedirectMiddleware)
    app.add_middleware(SecurityHeadersMiddleware)
    app.add_middleware(InMemoryRateLimiter)
    app.add_middleware(
        CSRFProtectionMiddleware,
        exempt_prefixes=[
            "/ws/",
            "/oauth/",
            "/api/v1/audio/",
            "/health",
            "/healthz",
            "/livez",
            "/readyz",
        ],
    )

    # Function-based middleware
    @app.middleware("http")
    async def commit_session_after_request(request: Request, call_next):
        response = await call_next(request)
        Session.commit()
        return response

    @app.middleware("http")
    async def check_url(request: Request, call_next):
        start_time = int(time.time())
        request.state.enable_api_key = app.state.config.ENABLE_API_KEY
        response = await call_next(request)
        response.headers["X-Process-Time"] = str(int(time.time()) - start_time)
        return response

    @app.middleware("http")
    async def inspect_websocket(request: Request, call_next):
        if (
            "/ws/socket.io" in request.url.path
            and request.query_params.get("transport") == "websocket"
        ):
            upgrade = (request.headers.get("Upgrade") or "").lower()
            connection = (request.headers.get("Connection") or "").lower().split(",")
            if upgrade != "websocket" or "upgrade" not in connection:
                return JSONResponse(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    content={"detail": "Invalid WebSocket upgrade request"},
                )
        return await call_next(request)

    # CORS
    if CORS_ALLOW_ORIGIN and CORS_ALLOW_ORIGIN != [""]:
        origins = CORS_ALLOW_ORIGIN
        if "*" in origins:
            log.warning(
                "CORS: Wildcard origin ('*') is configured with allow_credentials=True. "
                "This combination is rejected by browsers. Removing wildcard and falling back to Same-Origin."
            )
            origins = [o for o in origins if o != "*"]
        if origins:
            app.add_middleware(
                CORSMiddleware,
                allow_origins=origins,
                allow_credentials=True,
                allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
                allow_headers=[
                    "Authorization",
                    "Content-Type",
                    "Accept",
                    "X-CSRF-Token",
                    "X-Request-ID",
                ],
            )
    else:
        log.info(
            "CORS: No origins configured (CORS_ALLOW_ORIGIN is empty). Same-origin policy enforced."
        )

    # Session middleware (required by authlib for OAuth)
    if len(OAUTH_PROVIDERS) > 0:
        app.add_middleware(
            SessionMiddleware,
            secret_key=BCGPT_SECRET_KEY,
            session_cookie="oui-session",
            same_site=BCGPT_SESSION_COOKIE_SAME_SITE,
            https_only=BCGPT_SESSION_COOKIE_SECURE,
        )

    # Audit logging (added last so it wraps everything)
    app.add_middleware(AuditLoggingMiddleware, starlette_app=app)


# =========================================================================
# Exception handler registration
# =========================================================================


def _register_exception_handlers(app: FastAPI) -> None:
    """Register structured exception handlers that emit a request_id.

    Without this the handlers in utils/error_handlers.py are dead code and
    every unhandled error returns a plain ``{"detail": "Internal Server Error"}``
    response with no correlation id. See ADR in
    docs/ERROR_HANDLING_RESILIENCE_GOVERNANCE_PLAN_2026-06-23.md §3.3.
    """
    app.add_exception_handler(Exception, generic_exception_handler)
    app.add_exception_handler(RequestValidationError, validation_exception_handler)
    app.add_exception_handler(StarletteHTTPException, http_exception_handler)


# =========================================================================
# Router registration
# =========================================================================


def _register_routes(app: FastAPI) -> None:
    """Mount all API routers and the WebSocket sub-app."""

    # WebSocket
    app.mount("/ws", socket_app)

    # LLM providers
    app.include_router(ollama.router, prefix="/ollama", tags=["ollama"])
    app.include_router(openai.router, prefix="/openai", tags=["openai"])
    # Gemini/Claude are config-style routers accessed via the `/api/v1` apiClient
    # (like tasks/images/audio), so they mount under /api/v1 — not at root like
    # the openai/ollama chat-completion proxies. Wrong prefix => SPA fallback 405.
    app.include_router(gemini.router, prefix="/api/v1/gemini", tags=["gemini"])
    app.include_router(claude.router, prefix="/api/v1/claude", tags=["claude"])

    # API v1 routers
    app.include_router(pipelines.router, prefix="/api/v1/pipelines", tags=["pipelines"])
    app.include_router(tasks.router, prefix="/api/v1/tasks", tags=["tasks"])
    app.include_router(images.router, prefix="/api/v1/images", tags=["images"])
    app.include_router(audio.router, prefix="/api/v1/audio", tags=["audio"])
    app.include_router(security.router, prefix="/api/v1/security", tags=["security"])
    app.include_router(
        security_events.router,
        prefix="/api/v1/security",
        tags=["security-events"],
    )
    app.include_router(audit.router, prefix="/api/v1/audit", tags=["audit"])
    app.include_router(usage.router, prefix="/api/v1/usage", tags=["usage"])
    app.include_router(dashboard.router, prefix="/api/v1/dashboard", tags=["dashboard"])
    app.include_router(scim.router, prefix="/api/v1/scim/v2", tags=["scim"])
    app.include_router(handoff.router, prefix="/api/v1/handoff", tags=["handoff"])
    app.include_router(retrieval.router, prefix="/api/v1/retrieval", tags=["retrieval"])
    app.include_router(configs.router, prefix="/api/v1/configs", tags=["configs"])
    app.include_router(auths.router, prefix="/api/v1/auths", tags=["auths"])
    app.include_router(users.router, prefix="/api/v1/users", tags=["users"])
    app.include_router(channels.router, prefix="/api/v1/channels", tags=["channels"])
    app.include_router(chats.router, prefix="/api/v1/chats", tags=["chats"])
    app.include_router(models.router, prefix="/api/v1/models", tags=["models"])
    app.include_router(knowledge.router, prefix="/api/v1/knowledge", tags=["knowledge"])
    app.include_router(prompts.router, prefix="/api/v1/prompts", tags=["prompts"])
    app.include_router(tools.router, prefix="/api/v1/tools", tags=["tools"])
    app.include_router(memories.router, prefix="/api/v1/memories", tags=["memories"])
    app.include_router(folders.router, prefix="/api/v1/folders", tags=["folders"])
    app.include_router(groups.router, prefix="/api/v1/groups", tags=["groups"])
    app.include_router(files.router, prefix="/api/v1/files", tags=["files"])
    app.include_router(functions.router, prefix="/api/v1/functions", tags=["functions"])
    app.include_router(
        evaluations.router, prefix="/api/v1/evaluations", tags=["evaluations"]
    )
    app.include_router(utils.router, prefix="/api/v1/utils", tags=["utils"])

    # Agent subsystem
    app.include_router(agents_router.router, prefix="/api/v1/agents", tags=["agents"])
    app.include_router(
        multi_agent_router.router,
        prefix="/api/v1/agents/multi-agent",
        tags=["multi-agent"],
    )
    app.include_router(skills_router.router, prefix="/api/v1/skills", tags=["skills"])
    app.include_router(mcp_router.router, prefix="/api/v1/mcp", tags=["mcp"])

    app.include_router(
        compliance_inventory.router,
        prefix="/api/v1/compliance/inventory",
        tags=["compliance-inventory"],
    )
    app.include_router(
        compliance_aiia.router,
        prefix="/api/v1/compliance/aiia",
        tags=["compliance-aiia"],
    )
    app.include_router(
        compliance_incidents.router,
        prefix="/api/v1/compliance/incidents",
        tags=["compliance-incidents"],
    )
    app.include_router(
        compliance_fairness.router,
        prefix="/api/v1/compliance/fairness",
        tags=["compliance-fairness"],
    )
    app.include_router(
        compliance_dsar.router,
        prefix="/api/v1/compliance/dsar",
        tags=["compliance-dsar"],
    )
    app.include_router(
        compliance_vendor.router,
        prefix="/api/v1/compliance/vendors",
        tags=["compliance-vendor"],
    )
    app.include_router(
        compliance_dashboard.router,
        prefix="/api/v1/compliance/dashboard",
        tags=["compliance-dashboard"],
    )
    app.include_router(
        hitl_router,
        prefix="/api/v1/compliance/hitl",
        tags=["compliance-hitl"],
    )


# =========================================================================
# Observability setup
# =========================================================================


def _setup_observability(app: FastAPI) -> None:
    """Configure OpenTelemetry, LangFuse, and Prometheus when enabled."""

    if ENABLE_OTEL:
        from bcgpt.utils import setup as setup_opentelemetry

        setup_opentelemetry(app=app, db_engine=engine)

        if RAG_TRACING_ENABLED:
            from bcgpt.utils.langfuse_tracing import setup_langfuse_tracing
            from opentelemetry import trace

            setup_langfuse_tracing(
                tracer_provider=trace.get_tracer_provider(),
                public_key=LANGFUSE_PUBLIC_KEY,
                secret_key=LANGFUSE_SECRET_KEY,
                host=LANGFUSE_HOST,
            )

    if PROMETHEUS_METRICS_ENABLED:
        from bcgpt.utils.prometheus_metrics import init_metrics, setup_instrumentator

        init_metrics()
        setup_instrumentator(app)


# =========================================================================
# Static files & SPA fallback
# =========================================================================


def _mount_static_files(app: FastAPI) -> None:
    """Serve static assets, cache directory, and SPA frontend."""

    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
    app.mount("/cache", StaticFiles(directory=CACHE_DIR), name="cache")

    # Swagger UI customization
    def swagger_ui_html(*args, **kwargs):
        return get_swagger_ui_html(
            *args,
            **kwargs,
            swagger_js_url="/static/swagger-ui/swagger-ui-bundle.js",
            swagger_css_url="/static/swagger-ui/swagger-ui.css",
            swagger_favicon_url="/static/swagger-ui/favicon.png",
        )

    applications.get_swagger_ui_html = swagger_ui_html

    # Frontend SPA
    if os.path.exists(FRONTEND_BUILD_DIR):
        mimetypes.add_type("text/javascript", ".js")
        app.mount(
            "/",
            SPAStaticFiles(directory=FRONTEND_BUILD_DIR, html=True),
            name="spa-static-files",
        )
    else:
        log.warning(
            f"Frontend build directory not found at '{FRONTEND_BUILD_DIR}'. Serving API only."
        )


# =========================================================================
# Helper utilities
# =========================================================================


def _get_config_value(val: Any) -> Any:
    """Unwrap a PersistentConfig to its underlying value."""
    from bcgpt.config import PersistentConfig

    if isinstance(val, PersistentConfig):
        return val.value
    return val


# =========================================================================
# Background tasks
# =========================================================================


async def _audit_retention_task(app: FastAPI) -> None:
    """Periodically purge expired audit logs based on retention config."""
    while True:
        await asyncio.sleep(86400)
        try:
            retention_days = int(
                _get_config_value(app.state.config.AUDIT_RETENTION_DAYS)
            )
            from bcgpt.models.audit_log import AuditLogs

            deleted = AuditLogs.purge_expired(retention_days)
            if deleted > 0:
                log.info(
                    f"Auto-purged {deleted} audit logs older than {retention_days} days"
                )
        except Exception as e:
            log.error(f"Failed to auto-purge audit logs: {e}")


async def _chat_retention_task(app: FastAPI) -> None:
    """Periodically enforce chat data retention (anonymize or purge) — 2.4."""
    while True:
        await asyncio.sleep(86400)
        try:
            days = int(_get_config_value(app.state.config.CHAT_RETENTION_DAYS) or 0)
            if days <= 0:
                continue
            from bcgpt.models.chats import Chats

            if _get_config_value(app.state.config.CHAT_RETENTION_ANONYMIZE):
                n = Chats.anonymize_chats_older_than(days)
                if n:
                    log.info(f"Anonymized {n} chats older than {days} days")
            else:
                n = Chats.delete_chats_older_than(days)
                if n:
                    log.info(f"Purged {n} chats older than {days} days")
        except Exception as e:
            log.error(f"Failed chat retention task: {e}")


async def _compliance_retention_task(app: FastAPI) -> None:
    """Daily compliance maintenance: AIIA expiry check + provenance purge."""
    while True:
        await asyncio.sleep(86400)
        try:
            if not _get_config_value(app.state.config.COMPLIANCE_ENABLED):
                continue

            if _get_config_value(app.state.config.COMPLIANCE_AIIA_ENABLED):
                from bcgpt.compliance.models.aiia import AIIARecords

                expired = AIIARecords.get_expired()
                if expired:
                    log.warning(
                        "AIIA: %d impact assessments have expired and need re-assessment",
                        len(expired),
                    )

            if _get_config_value(app.state.config.COMPLIANCE_PROVENANCE_ENABLED):
                from bcgpt.compliance.models.provenance import AIRAGProvenances

                purged = AIRAGProvenances.purge_expired()
                if purged:
                    log.info("Provenance: purged %d expired records", purged)

        except Exception as e:
            log.error(f"Failed compliance retention task: {e}")


# =========================================================================
# Lifespan (startup / shutdown)
# =========================================================================


@asynccontextmanager
async def lifespan(app: FastAPI):
    start_logger()

    # Validate configuration
    from bcgpt.settings import validate_settings

    try:
        warnings = validate_settings()
        for w in warnings:
            log.warning(f"Config warning: {w}")
    except ValueError as e:
        log.error(f"Configuration validation failed: {e}")
        if os.environ.get("ENV", "prod") != "dev":
            raise

    if RESET_CONFIG_ON_START:
        reset_config()

    if LICENSE_KEY:
        get_license_data(app, LICENSE_KEY)

    init_providers(app.state.config)

    # Seed default LLM model pricing for FinOps cost computation (2.1), opt-in.
    if app.state.config.TOKEN_USAGE_PERSIST_ENABLED:
        try:
            from bcgpt.models.token_usage import ModelPricings

            seeded = ModelPricings.seed_defaults()
            if seeded:
                log.info("Seeded %d default model_pricing rows", seeded)
        except Exception as e:
            log.warning("Could not seed model pricing: %s", e)

    # Seed curated built-in skills (idempotent).
    try:
        from bcgpt.utils.skill_seeds import seed_builtin_skills

        seeded_skills = seed_builtin_skills()
        if seeded_skills:
            log.info("Seeded %d built-in skills", seeded_skills)
    except Exception as e:
        log.warning("Built-in skill seeding skipped: %s", e)

    # Load the persisted GraphRAG knowledge graph into memory (3.1), opt-in.
    if app.state.config.RAG_GRAPH_ENABLED:
        try:
            from bcgpt.retrieval.graph.graph_builder import load_graph_from_db

            nodes = load_graph_from_db()
            log.info("Loaded knowledge graph from DB (%d nodes)", nodes)
        except Exception as e:
            log.warning("Could not load knowledge graph: %s", e)

    # --- MCP built-in servers (in-process Streamable HTTP) ---
    # FastAPI does not propagate ASGI lifespan to mounted Starlette sub-apps, so
    # each built-in's session_manager.run() must be entered here via AsyncExitStack
    # (else RuntimeError "Task group is not initialized"). Built-ins are loopback
    # only — do NOT expose /mcp/builtin/* through a public reverse proxy.
    import contextlib as _contextlib

    from bcgpt.mcpbridge.builtins import fetch as _builtin_fetch
    from bcgpt.mcpbridge.builtins import time as _builtin_time

    app.state.mcp_exit_stack = _contextlib.AsyncExitStack()
    _builtin_factories = {
        _builtin_time.BUILTIN_NAME: _builtin_time.create_server,
        _builtin_fetch.BUILTIN_NAME: _builtin_fetch.create_server,
    }
    for _name in list(
        getattr(app.state.config.MCP_BUILTINS_ENABLED, "value", []) or []
    ):
        _factory = _builtin_factories.get(_name)
        if _factory is None:
            continue
        try:
            _mcp_app = _factory()
            _asgi = _mcp_app.streamable_http_app()  # materialize session_manager
            app.mount(f"/mcp/builtin/{_name}", _asgi)
            await app.state.mcp_exit_stack.enter_async_context(
                _mcp_app.session_manager.run()
            )
            log.info("Started built-in MCP server: %s", _name)
        except Exception as e:
            log.warning("Failed to start built-in MCP %s: %s", _name, e)

    # Background tasks
    cleanup_task = asyncio.create_task(periodic_usage_pool_cleanup())
    audit_task = asyncio.create_task(_audit_retention_task(app))
    chat_retention_task = asyncio.create_task(_chat_retention_task(app))
    compliance_task = asyncio.create_task(_compliance_retention_task(app))

    yield

    # ── Graceful shutdown ──────────────────────────────────────────────
    try:
        await app.state.mcp_exit_stack.aclose()
    except Exception as e:
        log.warning("MCP built-in shutdown error: %s", e)
    for task in (cleanup_task, audit_task, chat_retention_task, compliance_task):
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass

    await close_client_session()

    for _cleanup in (
        _shutdown_vector_db,
        _shutdown_telemetry,
        _shutdown_db_engine,
    ):
        try:
            _cleanup()
        except Exception:
            pass


def _shutdown_vector_db() -> None:
    from bcgpt.retrieval.vector.connector import VECTOR_DB_CLIENT

    if hasattr(VECTOR_DB_CLIENT, "close"):
        VECTOR_DB_CLIENT.close()


def _shutdown_telemetry() -> None:
    from opentelemetry import trace

    provider = trace.get_tracer_provider()
    if hasattr(provider, "shutdown"):
        provider.shutdown()


def _shutdown_db_engine() -> None:
    from bcgpt.internal.db import engine as db_engine

    if db_engine:
        db_engine.dispose()


# =========================================================================
# Application assembly
# =========================================================================

app = FastAPI(
    docs_url="/docs" if ENV == "dev" else None,
    openapi_url="/openapi.json" if ENV == "dev" else None,
    redoc_url=None,
    lifespan=lifespan,
)

oauth_manager = OAuthManager(app)

app.state.config = AppConfig(
    redis_url=REDIS_URL,
    redis_sentinels=get_sentinels_from_env(REDIS_SENTINEL_HOSTS, REDIS_SENTINEL_PORT),
)

_apply_config(app)
_setup_observability(app)
_init_embeddings(app)
_setup_middleware(app)
_register_exception_handlers(app)
_register_routes(app)


# =========================================================================
# Chat endpoints
# =========================================================================


@app.get("/api/models")
async def get_models(request: Request, user=Depends(get_verified_user)):
    def _filter_models_for_user(models: list, user) -> list:
        filtered = []
        for model in models:
            if model.get("arena"):
                if has_access(
                    user.id,
                    type="read",
                    access_control=model.get("info", {})
                    .get("meta", {})
                    .get("access_control", {}),
                ):
                    filtered.append(model)
                continue

            model_info = Models.get_model_by_id(model["id"])
            if model_info:
                if user.id == model_info.user_id or has_access(
                    user.id, type="read", access_control=model_info.access_control
                ):
                    filtered.append(model)
        return filtered

    all_models = await get_all_models(request, user=user)

    models = []
    for model in all_models:
        # Filter out filter pipelines
        if "pipeline" in model and model["pipeline"].get("type", None) == "filter":
            continue

        model_tags = [
            tag.get("name")
            for tag in model.get("info", {}).get("meta", {}).get("tags", [])
        ]
        tags = [tag.get("name") for tag in model.get("tags", [])]
        tags = list(set(model_tags + tags))
        model["tags"] = [{"name": tag} for tag in tags]
        models.append(model)

    model_order_list = request.app.state.config.MODEL_ORDER_LIST
    if model_order_list:
        order_map = {mid: i for i, mid in enumerate(model_order_list)}
        models.sort(key=lambda x: (order_map.get(x["id"], float("inf")), x["name"]))

    if user.role == "user" and not BYPASS_MODEL_ACCESS_CONTROL:
        models = _filter_models_for_user(models, user)

    log.debug(
        f"/api/models returned filtered models accessible to the user: "
        f"{json.dumps([m['id'] for m in models])}"
    )
    return {"data": models}


@app.get("/api/models/base")
async def get_base_models(request: Request, user=Depends(get_admin_user)):
    models = await get_all_base_models(request, user=user)
    return {"data": models}


def _public_generation_payload(generation) -> dict[str, Any]:
    """Serialize generation authority without user IDs or request fingerprints."""

    return {
        "generation_id": generation.generation_id,
        "turn_id": generation.turn_id,
        "client_message_id": generation.client_message_id,
        "message_id": generation.assistant_message_id,
        "chat_id": generation.chat_id,
        "model_id": generation.model_id,
        "task_id": generation.task_id,
        "status": generation.status,
        "terminal_reason": generation.terminal_reason,
        "version": generation.version,
        "created_at": generation.created_at,
        "updated_at": generation.updated_at,
        "terminal_at": generation.terminal_at,
        "durable": True,
    }


def _public_replay_payload(replay) -> dict[str, Any] | None:
    if replay is None:
        return None
    return {
        "content": replay.content,
        "cursor": replay.last_sequence,
        "status": replay.status,
        "degraded": replay.degraded,
        "expires_at": replay.expires_at,
    }


def _generation_admission_response(result) -> dict[str, Any]:
    generation = result.generation
    terminal = generation.status in ("completed", "stopped", "error", "timed_out")
    return {
        "status": result.kind == "duplicate" and not terminal,
        "task_id": generation.task_id,
        "generation_id": generation.generation_id,
        "chat_id": generation.chat_id,
        "message_id": generation.assistant_message_id,
        "admission": {
            "status": result.kind,
            "accepted": result.kind == "duplicate" and not terminal,
            "terminal": terminal,
            "stopped": generation.status == "stopped",
            "durable": True,
            "generation": _public_generation_payload(generation),
        },
    }


async def _terminalize_admitted_generation(
    generation_request, status_value: str, reason: str
) -> None:
    """Persist both durable authority and the assistant's terminal projection."""

    generation = await asyncio.to_thread(
        ChatGenerations.terminalize,
        generation_request.generation_id,
        generation_request.user_id,
        status_value,
        reason,
    )
    if generation is None:
        return
    await asyncio.to_thread(
        Chats.upsert_message_to_chat_by_id_and_message_id,
        generation.chat_id,
        generation.assistant_message_id,
        {
            "done": True,
            "generationId": generation.generation_id,
            "generationStatus": generation.status,
            "terminalReason": generation.terminal_reason,
        },
    )


@app.post("/api/chat/completions")
async def chat_completion(
    request: Request,
    form_data: dict,
    user=Depends(get_verified_user),
):
    if not request.app.state.MODELS:
        await get_all_models(request, user=user)

    model_item = form_data.pop("model_item", {})
    tasks = form_data.pop("background_tasks", None)
    generation_request = None
    generation_admitted = False
    metadata: dict[str, Any] = {}

    try:
        model_id = form_data.get("model", None)
        if not model_item.get("direct", False):
            if model_id not in request.app.state.MODELS:
                raise Exception("Model not found")

            model = request.app.state.MODELS[model_id]
            model_info = Models.get_model_by_id(model_id)

            if not BYPASS_MODEL_ACCESS_CONTROL and user.role == "user":
                check_model_access(user, model)
        else:
            model = model_item
            model_info = None
            request.state.direct = True
            request.state.model = model

        try:
            generation_request = parse_chat_generation_request(
                form_data,
                user_id=user.id,
                model_id=model_id,
            )
        except ChatGenerationValidationError as exc:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=str(exc),
            ) from exc

        if generation_request is not None:
            try:
                await asyncio.to_thread(
                    verify_chat_generation_message_proof, generation_request
                )
            except ChatGenerationValidationError as exc:
                raise HTTPException(
                    status_code=status.HTTP_403_FORBIDDEN,
                    detail=str(exc),
                ) from exc

            admission = await asyncio.to_thread(
                ChatGenerations.admit,
                generation_id=generation_request.generation_id,
                turn_id=generation_request.turn_id,
                client_message_id=generation_request.client_message_id,
                assistant_message_id=generation_request.assistant_message_id,
                user_id=generation_request.user_id,
                chat_id=generation_request.chat_id,
                model_id=generation_request.model_id,
            )
            if admission.kind == "conflict":
                raise HTTPException(
                    status_code=status.HTTP_409_CONFLICT,
                    detail="Generation idempotency authority conflicts with an existing request",
                )
            if admission.kind != "accepted":
                if admission.generation.status in (
                    "completed",
                    "stopped",
                    "error",
                    "timed_out",
                ):
                    await asyncio.to_thread(
                        Chats.upsert_message_to_chat_by_id_and_message_id,
                        generation_request.chat_id,
                        generation_request.assistant_message_id,
                        {
                            "done": True,
                            "generationId": generation_request.generation_id,
                            "generationStatus": admission.generation.status,
                            "terminalReason": admission.generation.terminal_reason,
                        },
                    )
                return _generation_admission_response(admission)

            generation_admitted = True
            await asyncio.to_thread(
                Chats.upsert_message_to_chat_by_id_and_message_id,
                generation_request.chat_id,
                generation_request.assistant_message_id,
                {
                    "generationId": generation_request.generation_id,
                    "turnId": generation_request.turn_id,
                    "generationStatus": "admitted",
                    "done": False,
                },
            )

        metadata = {
            "user_id": user.id,
            "chat_id": form_data.pop("chat_id", None),
            "message_id": form_data.pop("id", None),
            "session_id": form_data.pop("session_id", None),
            "tool_ids": form_data.get("tool_ids", None),
            "tool_servers": form_data.pop("tool_servers", None),
            "skill_ids": form_data.pop("skill_ids", None),
            "files": form_data.get("files", None),
            "features": form_data.get("features", None),
            "variables": form_data.get("variables", None),
            "model": model,
            "direct": model_item.get("direct", False),
            **(
                {
                    "generation_id": generation_request.generation_id,
                    "turn_id": generation_request.turn_id,
                    "client_message_id": generation_request.client_message_id,
                }
                if generation_request is not None
                else {}
            ),
            **(
                {"function_calling": "native"}
                if form_data.get("params", {}).get("function_calling") == "native"
                or (
                    model_info
                    and model_info.params.model_dump().get("function_calling")
                    == "native"
                )
                else {}
            ),
        }

        # Stamp the request start for end-to-end AI-interaction latency (1.5).
        # `metadata` is the same dict later handed to process_chat_response.
        metadata["__chat_start_ts__"] = time.time()

        request.state.metadata = metadata
        form_data["metadata"] = metadata
        for field in ("generation_id", "turn_id", "client_message_id"):
            form_data.pop(field, None)

        form_data, metadata, events = await process_chat_payload(
            request, form_data, user, metadata, model
        )

    except HTTPException:
        if generation_request is not None and generation_admitted:
            await _terminalize_admitted_generation(
                generation_request,
                "error",
                "request_rejected",
            )
        raise
    except Exception as e:
        log.error(f"Error processing chat payload: {e}", exc_info=True)
        if generation_request is not None and generation_admitted:
            await _terminalize_admitted_generation(
                generation_request,
                "error",
                "payload_error",
            )
        if metadata.get("chat_id") and metadata.get("message_id"):
            Chats.upsert_message_to_chat_by_id_and_message_id(
                metadata["chat_id"],
                metadata["message_id"],
                {"error": {"content": str(e)}},
            )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )

    try:
        response = await chat_completion_handler(request, form_data, user)
        return await process_chat_response(
            request, response, form_data, user, metadata, model, events, tasks
        )
    except Exception as e:
        log.error(f"Error in chat completion handler/response: {e}", exc_info=True)
        if generation_request is not None and generation_admitted:
            await _terminalize_admitted_generation(
                generation_request,
                "error",
                "provider_dispatch_error",
            )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )


# Aliases for backward compatibility
generate_chat_completions = chat_completion
generate_chat_completion = chat_completion


class ChatGenerationBindingForm(BaseModel):
    chat_id: str
    message_id: str


async def _verified_generation_binding(
    generation_id: str, chat_id: str, message_id: str, user_id: str
) -> tuple[str, str, str]:
    try:
        normalized_generation_id = parse_uuid(generation_id, "generation_id")
        normalized_chat_id = parse_uuid(chat_id, "chat_id")
        normalized_message_id = parse_uuid(message_id, "message_id")
    except ChatGenerationValidationError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc

    proof_valid = await asyncio.to_thread(
        verify_assistant_message_authority,
        user_id=str(user_id),
        chat_id=normalized_chat_id,
        assistant_message_id=normalized_message_id,
    )
    if not proof_valid:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat generation authority not found",
        )
    return normalized_generation_id, normalized_chat_id, normalized_message_id


@app.get("/api/chat/{chat_id}/generations")
async def list_active_chat_generations(chat_id: str, user=Depends(get_verified_user)):
    try:
        normalized_chat_id = parse_uuid(chat_id, "chat_id")
    except ChatGenerationValidationError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc

    chat = await asyncio.to_thread(
        Chats.get_chat_by_id_and_user_id, normalized_chat_id, user.id
    )
    if chat is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat generation authority not found",
        )
    generations = await asyncio.to_thread(
        ChatGenerations.list_active_by_chat, user.id, normalized_chat_id
    )
    replays = await asyncio.gather(
        *(
            asyncio.to_thread(
                ChatGenerations.get_replay_snapshot, item.generation_id, user.id
            )
            for item in generations
        )
    )
    payloads = []
    for generation, replay in zip(generations, replays):
        payload = _public_generation_payload(generation)
        payload["replay"] = _public_replay_payload(replay)
        payloads.append(payload)
    return {"generations": payloads}


@app.get("/api/chat/generations/{generation_id}")
async def get_chat_generation_status(
    generation_id: str,
    chat_id: str,
    message_id: str,
    user=Depends(get_verified_user),
):
    normalized_generation_id, normalized_chat_id, normalized_message_id = (
        await _verified_generation_binding(generation_id, chat_id, message_id, user.id)
    )
    generation = await asyncio.to_thread(
        ChatGenerations.get_owned, normalized_generation_id, user.id
    )
    if (
        generation is None
        or generation.chat_id != normalized_chat_id
        or generation.assistant_message_id != normalized_message_id
    ):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat generation authority not found",
        )
    replay = await asyncio.to_thread(
        ChatGenerations.get_replay_snapshot, normalized_generation_id, user.id
    )
    payload = _public_generation_payload(generation)
    payload["replay"] = _public_replay_payload(replay)
    return payload


@app.get("/api/chat/generations/{generation_id}/events")
async def get_chat_generation_events(
    generation_id: str,
    chat_id: str,
    message_id: str,
    after: int = 0,
    limit: int = 256,
    user=Depends(get_verified_user),
):
    normalized_generation_id, _, _ = await _verified_generation_binding(
        generation_id, chat_id, message_id, user.id
    )
    if after < 0 or limit < 1 or limit > 256:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid generation replay cursor",
        )
    tail = await asyncio.to_thread(
        ChatGenerations.get_replay_tail,
        normalized_generation_id,
        user.id,
        after_sequence=after,
        limit=limit,
    )
    if tail is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat generation replay not found",
        )
    return {
        "generation_id": normalized_generation_id,
        "chat_id": chat_id,
        "message_id": message_id,
        **tail,
    }


@app.post("/api/chat/generations/{generation_id}/stop")
async def stop_chat_generation(
    generation_id: str,
    form_data: ChatGenerationBindingForm,
    user=Depends(get_verified_user),
):
    normalized_generation_id, normalized_chat_id, normalized_message_id = (
        await _verified_generation_binding(
            generation_id, form_data.chat_id, form_data.message_id, user.id
        )
    )
    durable_stop = await asyncio.to_thread(
        ChatGenerations.request_stop,
        generation_id=normalized_generation_id,
        user_id=user.id,
        chat_id=normalized_chat_id,
        assistant_message_id=normalized_message_id,
    )
    if durable_stop.kind == "different_generation":
        # Do not disclose whether a conflicting generation belongs to another
        # user or chat.
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat generation authority not found",
        )

    live_stop = None
    generation = durable_stop.generation
    if durable_stop.kind == "accepted":
        live_stop = await stop_generation(
            normalized_generation_id,
            owner_id=user.id,
            chat_id=normalized_chat_id,
            message_id=normalized_message_id,
        )
        if live_stop is not None and live_stop.get("stopped"):
            generation = await asyncio.to_thread(
                ChatGenerations.terminalize,
                normalized_generation_id,
                user.id,
                "stopped",
                "user_requested",
            )
        elif generation.task_id is None:
            # A Stop that wins before provider task binding is a terminal
            # tombstone. The later binder must observe it and refuse dispatch.
            generation = await asyncio.to_thread(
                ChatGenerations.terminalize,
                normalized_generation_id,
                user.id,
                "stopped",
                "user_requested_before_task_binding",
            )

    if generation is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Could not confirm chat generation stop",
        )

    terminal = generation.status in ("completed", "stopped", "error", "timed_out")
    stopped = generation.status == "stopped"
    observed = bool(live_stop and live_stop.get("observed"))
    if terminal:
        await asyncio.to_thread(
            Chats.upsert_message_to_chat_by_id_and_message_id,
            normalized_chat_id,
            normalized_message_id,
            {
                "done": True,
                "generationId": normalized_generation_id,
                "generationStatus": generation.status,
                "terminalReason": generation.terminal_reason,
            },
        )

    receipt = {
        "status": "observed" if observed else durable_stop.kind,
        "accepted": durable_stop.kind in ("accepted", "already_terminal"),
        "observed": observed,
        "terminal": terminal,
        "stopped": stopped,
        "durable": True,
        "task_id": generation.task_id,
        "generation_id": generation.generation_id,
        "chat_id": generation.chat_id,
        "message_id": generation.assistant_message_id,
        "generation": _public_generation_payload(generation),
    }
    replay = await asyncio.to_thread(
        ChatGenerations.get_replay_snapshot, normalized_generation_id, user.id
    )
    receipt["generation"]["replay"] = _public_replay_payload(replay)
    return JSONResponse(
        receipt,
        status_code=(
            status.HTTP_202_ACCEPTED
            if receipt["accepted"] and not receipt["terminal"]
            else status.HTTP_200_OK
        ),
    )


@app.post("/api/chat/completed")
async def chat_completed(
    request: Request, form_data: dict, user=Depends(get_verified_user)
):
    try:
        model_item = form_data.pop("model_item", {})
        if model_item.get("direct", False):
            request.state.direct = True
            request.state.model = model_item
        return await chat_completed_handler(request, form_data, user)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )


@app.post("/api/chat/actions/{action_id}")
async def chat_action(
    request: Request, action_id: str, form_data: dict, user=Depends(get_verified_user)
):
    try:
        model_item = form_data.pop("model_item", {})
        if model_item.get("direct", False):
            request.state.direct = True
            request.state.model = model_item
        return await chat_action_handler(request, action_id, form_data, user)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )


# =========================================================================
# Task management endpoints
# =========================================================================


class StopTaskForm(BaseModel):
    chat_id: str | None = None
    message_id: str | None = None


@app.post("/api/tasks/stop/{task_id}")
async def stop_task_endpoint(
    task_id: str,
    form_data: StopTaskForm | None = None,
    user=Depends(get_verified_user),
):
    try:
        result = await stop_task(
            task_id,
            owner_id=user.id,
            chat_id=form_data.chat_id if form_data else None,
            message_id=form_data.message_id if form_data else None,
        )
        return result
    except TaskNotFoundError as e:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))


@app.get("/api/tasks")
async def list_tasks_endpoint(user=Depends(get_verified_user)):
    return {"tasks": list_tasks(user.id)}


# =========================================================================
# Configuration endpoints
# =========================================================================


@app.get("/api/config")
async def get_app_config(request: Request):
    user = None
    if "token" in request.cookies:
        token = request.cookies.get("token")
        try:
            data = decode_token(token)
        except Exception as e:
            log.debug(e)
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token",
            )
        if data is not None and "id" in data:
            user = Users.get_user_by_id(data["id"])

    user_count = Users.get_num_users()
    onboarding = False

    if user is None:
        onboarding = user_count == 0

    return {
        **({"onboarding": True} if onboarding else {}),
        "status": True,
        "name": app.state.BCGPT_APP_NAME,
        "logo_url": app.state.config.BCGPT_LOGO_URL,
        "version": VERSION,
        "default_locale": str(DEFAULT_LOCALE),
        "oauth": {
            "providers": {
                name: config.get("name", name)
                for name, config in OAUTH_PROVIDERS.items()
            }
        },
        "features": {
            "auth": BCGPT_AUTH,
            "auth_trusted_header": bool(app.state.AUTH_TRUSTED_EMAIL_HEADER),
            "enable_ldap": app.state.config.ENABLE_LDAP,
            "enable_api_key": app.state.config.ENABLE_API_KEY,
            "enable_signup": app.state.config.ENABLE_SIGNUP,
            "enable_login_form": app.state.config.ENABLE_LOGIN_FORM,
            "enable_websocket": ENABLE_WEBSOCKET_SUPPORT,
            **(
                {
                    "enable_ollama_api": app.state.config.ENABLE_OLLAMA_API,
                    "enable_openai_api": app.state.config.ENABLE_OPENAI_API,
                    "enable_direct_connections": app.state.config.ENABLE_DIRECT_CONNECTIONS,
                    "enable_channels": app.state.config.ENABLE_CHANNELS,
                    "enable_web_search": app.state.config.ENABLE_RAG_WEB_SEARCH,
                    "enable_image_generation": app.state.config.ENABLE_IMAGE_GENERATION,
                    "enable_autocomplete_generation": app.state.config.ENABLE_AUTOCOMPLETE_GENERATION,
                    "enable_community_sharing": app.state.config.ENABLE_COMMUNITY_SHARING,
                    "enable_message_rating": app.state.config.ENABLE_MESSAGE_RATING,
                    "enable_user_webhooks": app.state.config.ENABLE_USER_WEBHOOKS,
                    "enable_admin_export": ENABLE_ADMIN_EXPORT,
                    "enable_admin_chat_access": ENABLE_ADMIN_CHAT_ACCESS,
                    "enable_google_drive_integration": app.state.config.ENABLE_GOOGLE_DRIVE_INTEGRATION,
                    "enable_onedrive_integration": app.state.config.ENABLE_ONEDRIVE_INTEGRATION,
                }
                if user is not None
                else {}
            ),
        },
        **(
            {
                "default_models": app.state.config.DEFAULT_MODELS,
                "default_prompt_suggestions": app.state.config.DEFAULT_PROMPT_SUGGESTIONS,
                "user_count": user_count,
                "audio": {
                    "tts": {
                        "engine": app.state.config.TTS_ENGINE,
                        "voice": app.state.config.TTS_VOICE,
                        "split_on": app.state.config.TTS_SPLIT_ON,
                    },
                    "stt": {
                        "engine": app.state.config.STT_ENGINE,
                    },
                },
                "file": {
                    "max_size": app.state.config.FILE_MAX_SIZE,
                    "max_count": app.state.config.FILE_MAX_COUNT,
                },
                "permissions": {**app.state.config.USER_PERMISSIONS},
                "google_drive": {
                    "client_id": GOOGLE_DRIVE_CLIENT_ID.value,
                    "api_key": GOOGLE_DRIVE_API_KEY.value,
                },
                "onedrive": {"client_id": ONEDRIVE_CLIENT_ID.value},
                "license_metadata": app.state.LICENSE_METADATA,
                **(
                    {"active_entries": app.state.USER_COUNT}
                    if user.role == "admin"
                    else {}
                ),
            }
            if user is not None
            else {}
        ),
    }


class UrlForm(BaseModel):
    url: str


@app.get("/api/webhook")
async def get_webhook_url(user=Depends(get_admin_user)):
    return {"url": app.state.config.WEBHOOK_URL}


@app.post("/api/webhook")
async def update_webhook_url(form_data: UrlForm, user=Depends(get_admin_user)):
    app.state.config.WEBHOOK_URL = form_data.url
    app.state.WEBHOOK_URL = app.state.config.WEBHOOK_URL
    return {"url": app.state.config.WEBHOOK_URL}


@app.get("/api/version")
async def get_app_version():
    return {"version": VERSION}


@app.get("/api/version/updates")
async def get_app_latest_release_version(user=Depends(get_verified_user)):
    if OFFLINE_MODE:
        log.debug(
            "Offline mode is enabled, returning current version as latest version"
        )
        return {"current": VERSION, "latest": VERSION}
    try:
        timeout = aiohttp.ClientTimeout(total=1)
        async with aiohttp.ClientSession(timeout=timeout, trust_env=True) as session:
            async with session.get(
                "https://api.github.com/repos/bccard-ai/bcgpt-webui/releases/latest"
            ) as response:
                response.raise_for_status()
                data = await response.json()
                latest_version = data["tag_name"]
                return {"current": VERSION, "latest": latest_version[1:]}
    except Exception as e:
        log.debug(e)
        return {"current": VERSION, "latest": VERSION}


@app.get("/api/changelog")
async def get_app_changelog():
    return {key: CHANGELOG[key] for idx, key in enumerate(CHANGELOG) if idx < 5}


# =========================================================================
# OAuth
# =========================================================================


@app.get("/oauth/{provider}/login")
async def oauth_login(provider: str, request: Request):
    return await oauth_manager.handle_login(request, provider)


@app.get("/oauth/{provider}/callback")
async def oauth_callback(provider: str, request: Request, response: Response):
    return await oauth_manager.handle_callback(request, provider, response)


# =========================================================================
# Manifest & OpenSearch
# =========================================================================


@app.get("/manifest.json")
async def get_manifest_json():
    return {
        "name": app.state.BCGPT_APP_NAME,
        "short_name": app.state.BCGPT_APP_NAME,
        "description": "BCGPT is an open, extensible, user-friendly interface for AI that adapts to your workflow.",
        "start_url": "/",
        "display": "standalone",
        "background_color": "#343541",
        "orientation": "natural",
        "icons": [
            {
                "src": "/static/logo.png",
                "type": "image/png",
                "sizes": "500x500",
                "purpose": "any",
            },
            {
                "src": "/static/logo.png",
                "type": "image/png",
                "sizes": "500x500",
                "purpose": "maskable",
            },
        ],
    }


@app.get("/opensearch.xml")
async def get_opensearch_xml():
    xml_content = rf"""
    <OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
    <ShortName>{app.state.BCGPT_APP_NAME}</ShortName>
    <Description>Search {app.state.BCGPT_APP_NAME}</Description>
    <InputEncoding>UTF-8</InputEncoding>
    <Image width="16" height="16" type="image/x-icon">{app.state.config.BCGPT_URL}/static/favicon.png</Image>
    <Url type="text/html" method="get" template="{app.state.config.BCGPT_URL}/?q={"{searchTerms}"}"/>
    <moz:SearchForm>{app.state.config.BCGPT_URL}</moz:SearchForm>
    </OpenSearchDescription>
    """
    return Response(content=xml_content, media_type="application/xml")


# =========================================================================
# Health checks
# =========================================================================


@app.get("/health")
async def healthcheck():
    return {"status": True}


@app.get("/health/db")
async def healthcheck_with_db():
    Session.execute(text("SELECT 1;")).all()
    return {"status": True}


# ── Kubernetes probes ──────────────────────────────────────────────────


def _db_health_check():
    with engine.connect() as conn:
        conn.execute(text("SELECT 1"))


def _qdrant_health_check():
    from bcgpt.retrieval.vector.connector import VECTOR_DB_CLIENT

    if (
        VECTOR_DB_CLIENT
        and hasattr(VECTOR_DB_CLIENT, "client")
        and VECTOR_DB_CLIENT.client
    ):
        VECTOR_DB_CLIENT.client.get_collections()
        return "ok"
    return "not_configured"


def _redis_health_check():
    if not REDIS_URL:
        return "not_configured"
    import redis as redis_lib

    r = redis_lib.Redis.from_url(str(REDIS_URL), socket_connect_timeout=3)
    try:
        r.ping()
        return "ok"
    finally:
        r.close()


@app.get("/healthz")
async def healthz():
    """Kubernetes liveness probe — process is alive."""
    return {"status": "alive"}


@app.get("/livez")
async def livez():
    """Kubernetes liveness probe with DB check."""
    try:
        await asyncio.wait_for(asyncio.to_thread(_db_health_check), timeout=5.0)
        return {"status": "alive", "db": "ok"}
    except Exception as e:
        raise HTTPException(
            status_code=503,
            detail={"status": "degraded", "db": "error", "error": str(e)},
        )


@app.get("/readyz")
async def readyz():
    """Kubernetes readiness probe — all dependencies available."""
    checks: dict[str, str] = {}
    all_ok = True

    try:
        await asyncio.wait_for(asyncio.to_thread(_db_health_check), timeout=5.0)
        checks["db"] = "ok"
    except Exception as e:
        checks["db"] = f"error: {e}"
        all_ok = False

    try:
        result = await asyncio.wait_for(
            asyncio.to_thread(_qdrant_health_check), timeout=5.0
        )
        checks["qdrant"] = result
    except Exception as e:
        checks["qdrant"] = f"error: {e}"
        all_ok = False

    try:
        result = await asyncio.wait_for(
            asyncio.to_thread(_redis_health_check), timeout=5.0
        )
        checks["redis"] = result
    except Exception as e:
        checks["redis"] = f"error: {e}"
        # Redis is optional — don't fail readiness

    if not all_ok:
        raise HTTPException(
            status_code=503,
            detail={"status": "not_ready", **checks},
        )
    return {"status": "ready", **checks}


# =========================================================================
# Static file mounts (must come after all routes)
# =========================================================================

_mount_static_files(app)
