<script lang="ts">
	import { get } from 'svelte/store';

	import { toast } from 'svelte-sonner';

	import { onMount, getContext } from 'svelte';
	import { models } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import type { i18n as i18nType } from 'i18next';
	import type { Writable } from 'svelte/store';

	const i18n: Writable<i18nType> = getContext<Writable<i18nType>>('i18n');

	/** Props for the RateComment component - message rating and feedback form */
	interface Props {
		/** The message object being rated */
		message: Record<string, unknown>;
		/** Whether the rating form is visible */
		show?: boolean;
		/** Callback when feedback is saved */
		onSave?: (data: Record<string, unknown>) => void;
	}

	// eslint-disable-next-line no-useless-assignment -- $bindable(false) default is read by parent, not this component
	let { message, show = $bindable(false), onSave = () => {} }: Props = $props();

	/** Reasons shown when the user likes a response */
	const LIKE_REASONS = [
		'accurate_information',
		'followed_instructions_perfectly',
		'showcased_creativity',
		'positive_attitude',
		'attention_to_detail',
		'thorough_explanation',
		'other'
	] as const;

	/** Reasons shown when the user dislikes a response */
	const DISLIKE_REASONS = [
		'dont_like_the_style',
		'too_verbose',
		'not_helpful',
		'not_factually_correct',
		'didnt_fully_follow_instructions',
		'refused_when_it_shouldnt_have',
		'being_lazy',
		'other'
	] as const;

	/** Maps reason keys to their i18n-translated labels */
	function getReasonLabel(reason: string): string {
		const labels: Record<string, string> = {
			accurate_information: $i18n.t('Accurate information'),
			followed_instructions_perfectly: $i18n.t('Followed instructions perfectly'),
			showcased_creativity: $i18n.t('Showcased creativity'),
			positive_attitude: $i18n.t('Positive attitude'),
			attention_to_detail: $i18n.t('Attention to detail'),
			thorough_explanation: $i18n.t('Thorough explanation'),
			dont_like_the_style: $i18n.t("Don't like the style"),
			too_verbose: $i18n.t('Too verbose'),
			not_helpful: $i18n.t('Not helpful'),
			not_factually_correct: $i18n.t('Not factually correct'),
			didnt_fully_follow_instructions: $i18n.t("Didn't fully follow instructions"),
			refused_when_it_shouldnt_have: $i18n.t("Refused when it shouldn't have"),
			being_lazy: $i18n.t('Being lazy'),
			other: $i18n.t('Other')
		};
		return labels[reason] ?? reason;
	}

	let tags = $state<Array<{ name: string }>>([]);
	let reasons = $state<readonly string[]>([]);
	let selectedReason = $state<string | null>(null);
	let comment = $state('');

	let detailedRating = $state<number | null>(null);
	let selectedModel = $state<Record<string, unknown> | null>(null);

	/** Initialises form state from existing message annotation data */
	function initFromMessage(): void {
		const annotation = message?.annotation as Record<string, unknown> | undefined;

		if (!selectedReason) {
			selectedReason = (annotation?.reason as string) ?? '';
		}

		if (!comment) {
			comment = (annotation?.comment as string) ?? '';
		}

		tags = ((annotation?.tags ?? []) as string[]).map((tag) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = (annotation?.details as Record<string, unknown>)?.rating as number | null;
		}
	}

	/** Persists the feedback and closes the form */
	function saveHandler(): void {
		onSave?.({
			reason: selectedReason,
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
	}

	$effect(() => {
		const rating = (message?.annotation as Record<string, unknown>)?.rating as number;
		if (rating === 1) {
			reasons = LIKE_REASONS;
		} else if (rating === -1) {
			reasons = DISLIKE_REASONS;
		}
	});

	$effect(() => {
		if (message) {
			initFromMessage();
		}
	});

	onMount(() => {
		if (message?.arena) {
			selectedModel = get(models).find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel
						? ((selectedModel as Record<string, unknown>)?.name ??
							(selectedModel as Record<string, unknown>)?.id)
						: message.selectedModelId
				})
			);
		}
	});
</script>

{#if message?.arena}
	<div class="text-xs font-medium pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel
				? ((selectedModel as Record<string, unknown>)?.name ??
					(selectedModel as Record<string, unknown>)?.id)
				: message.selectedModelId
		})}
	</div>
{/if}

<div
	class="my-2.5 rounded-xl px-4 py-3 border border-gray-100 dark:border-gray-850"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-medium">{$i18n.t('How would you rate this response?')}</div>

		<button
			aria-label={$i18n.t('Close')}
			onclick={() => {
				show = false;
			}}
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				viewBox="0 0 24 24"
				stroke-width="1.5"
				stroke="currentColor"
				class="size-4"
			>
				<path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
			</svg>
		</button>
	</div>

	<div class="w-full flex justify-center">
		<div class="relative w-fit">
			<div class="mt-1.5 w-fit flex gap-1 pb-5">
				{#each Array.from({ length: 10 }).map((_, i) => i + 1) as rating (rating)}
					<button
						class="size-7 text-sm border border-gray-100 dark:border-gray-850 hover:bg-gray-50 dark:hover:bg-gray-850 {detailedRating ===
						rating
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-full disabled:cursor-not-allowed disabled:text-gray-500 disabled:bg-white dark:disabled:bg-gray-900"
						onclick={() => {
							detailedRating = rating;
						}}
						disabled={(message?.annotation as Record<string, unknown>)?.rating === -1
							? rating > 5
							: rating < 6}
					>
						{rating}
					</button>
				{/each}
			</div>

			<div class="absolute bottom-0 left-0 right-0 flex justify-between text-xs">
				<div>
					1 - {$i18n.t('Awful')}
				</div>

				<div>
					10 - {$i18n.t('Amazing')}
				</div>
			</div>
		</div>
	</div>

	<div>
		{#if reasons.length > 0}
			<div class="text-sm mt-1.5 font-medium">{$i18n.t('Why?')}</div>

			<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
				{#each reasons as reason (reason)}
					<button
						class="px-3 py-0.5 border border-gray-100 dark:border-gray-850 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedReason ===
						reason
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-xl"
						onclick={() => {
							selectedReason = reason;
						}}
					>
						{getReasonLabel(reason)}
					</button>
				{/each}
			</div>
		{/if}
	</div>

	<div class="mt-2">
		<textarea
			bind:value={comment}
			class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl"
			placeholder={$i18n.t('Feel free to add specific details')}
			rows="3"
			aria-label="Feedback comment"
		></textarea>
	</div>

	<div class="mt-2 gap-1.5 flex justify-between">
		<div class="flex items-end group">
			<Tags
				{tags}
				onDelete={(e: CustomEvent) => {
					tags = tags.filter(
						(tag) =>
							tag.name.replaceAll(' ', '_').toLowerCase() !==
							e.detail.replaceAll(' ', '_').toLowerCase()
					);
				}}
				onAdd={(e: CustomEvent) => {
					tags = [...tags, { name: e.detail }];
				}}
			/>
		</div>

		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			onclick={saveHandler}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>
